update dropbear
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@58600 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/dropbear/.github/workflows/build.yml b/src/router/dropbear/.github/workflows/build.yml
--- a/src/router/dropbear/.github/workflows/build.yml
+++ b/src/router/dropbear/.github/workflows/build.yml
@@ -9,7 +9,7 @@ on:
       - master
 jobs:
   build:
-    runs-on: ${{ matrix.os || 'ubuntu-22.04' }}
+    runs-on: ${{ matrix.os || 'ubuntu-24.04' }}
     strategy:
       matrix:
         # XXX uncomment the line below to work with act, see https://github.com/nektos/act/issues/996
@@ -57,9 +57,12 @@ jobs:
           # early declarations so we specify it anyway.
           - name: c89
             extracflags: -std=c89 -Wdeclaration-after-statement
+            # enable all options
+            nondefault: 1
+            configure_flags: --enable-pam
 
-          - name: macos 12
-            os: macos-12
+          - name: macos 14
+            os: macos-14
             cc: clang
             # OS X says daemon() and utmp are deprecated.
             # OS X tests for undefined TARGET_OS_EMBEDDED in libc headers
@@ -70,16 +73,22 @@ jobs:
             # .../ranlib: file: libtomcrypt.a(cbc_setiv.o) has no symbols
             ranlib: ranlib -no_warning_for_no_symbols
 
-          - name: macos 11
-            os: macos-11
+          - name: macos 15
+            os: macos-15
             cc: clang
+            # OS X says daemon() and utmp are deprecated.
+            # OS X tests for undefined TARGET_OS_EMBEDDED in libc headers
             extracflags: -Wno-deprecated-declarations -Wno-undef
             runcheck: 'no'
             apt: 'no'
+            # fails with:
+            # .../ranlib: file: libtomcrypt.a(cbc_setiv.o) has no symbols
             ranlib: ranlib -no_warning_for_no_symbols
 
           # Check that debug code doesn't bitrot
           - name: DEBUG_TRACE
+            nondefault: 1
+            configure_flags: --enable-pam
             localoptions: |
               #define DEBUG_TRACE 5
 
@@ -87,8 +96,6 @@ jobs:
           - name: nondefault options
             nondefault: 1
             configure_flags: --enable-pam
-            localoptions: |
-              #define DROPBEAR_USE_SSH_CONFIG 1
 
           - name: most options disabled
             configure_flags: --disable-harden --disable-zlib --disable-openpty --disable-lastlog
@@ -189,7 +196,9 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: configure
-        run: ./configure $CONFIGURE_FLAGS CFLAGS="-O2 -Wall -Wno-pointer-sign $EXTRACFLAGS" --prefix="$HOME/inst" || (cat config.log; exit 1)
+        run: |
+          $CC --version || echo unknown $CC version
+          ./configure $CONFIGURE_FLAGS CFLAGS="-O2 -Wall -Wno-pointer-sign $EXTRACFLAGS" --prefix="$HOME/inst" || (cat config.log; exit 1)
 
       - name: nowritev
         if: ${{ matrix.nowritev }}
@@ -210,7 +219,9 @@ jobs:
           sed -i "s/DEFAULT_IDLE_TIMEOUT 1/DEFAULT_IDLE_TIMEOUT 99/" localoptions.h
 
       - name: make
-        run: make -j3 $MAKE_TARGET
+        run: |
+          cat localoptions.h
+          make -j3 $MAKE_TARGET
 
       - name: multilink
         if: ${{ matrix.multilink }}
@@ -239,6 +250,8 @@ jobs:
           # remove old files so we can rerun in-place with "act -r" during test development
           rm -vf ~/.ssh/id_dropbear*
           ~/inst/bin/dropbearkey -t ecdsa -f ~/.ssh/id_dropbear | grep ^ecdsa > ~/.ssh/authorized_keys
+          # Convert to openssh format so that asyncssh can find it in tests
+          ~/inst/bin/dropbearconvert dropbear openssh ~/.ssh/id_dropbear ~/.ssh/id_ecdsa
 
           # to test setting SSH_PUBKEYINFO, replace the trailing comment
           ~/inst/bin/dropbearkey -t ecdsa -f ~/.ssh/id_dropbear_key2 | grep ^ecdsa | sed 's/[^ ]*$/key2 extra/' >> ~/.ssh/authorized_keys
@@ -250,7 +263,7 @@ jobs:
         # upload config.log if something has failed
       - name: config.log
         if: ${{ !env.ACT && (failure() || cancelled()) }}
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: config.log
           path: config.log
