New DNSMasq version directly from Simon  -Improvements to lease time
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@7274 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/dnsmasq/debian/postrm b/src/router/dnsmasq/debian/postrm
--- a/src/router/dnsmasq/debian/postrm
+++ b/src/router/dnsmasq/debian/postrm
@@ -3,5 +3,9 @@ set -e
 
 if [ purge = "$1" ]; then
    update-rc.d dnsmasq remove >/dev/null
-   /usr/sbin/deluser dnsmasq
+   if [ -x "$(command -v deluser)" ]; then
+     deluser --quiet --system dnsmasq > /dev/null || true
+  else
+     echo >&2 "not removing dnsmasq system account because deluser command was not found"
+  fi
 fi
