asterisk update
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@16162 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/asterisk/build_tools/prep_tarball b/src/router/asterisk/build_tools/prep_tarball
--- a/src/router/asterisk/build_tools/prep_tarball
+++ b/src/router/asterisk/build_tools/prep_tarball
@@ -8,18 +8,27 @@
 make -C sounds MENUSELECT_CORE_SOUNDS=CORE-SOUNDS-EN-GSM MENUSELECT_MOH=MOH-OPSOUND-WAV WGET=wget DOWNLOAD=wget all
 make AWK=awk GREP=grep menuselect-tree
 
-make_tex_docs() {
-    # make backup of asterisk.tex because we are going to alter it
-    cp asterisk.tex asterisk.tex.orig
-    sed -e "s/ASTERISKVERSION/${VERSION}/" asterisk.tex > asterisk_local.tex
-    mv asterisk_local.tex asterisk.tex
-    rubber --pdf asterisk.tex
-    latex2html asterisk.tex
-    latex asterisk.tex
-    catdvi -e 1 -U asterisk.dvi | sed -re "s/\[U\+2022\]/*/g" | sed -re "s/\[U\+02C6\]/^/g" | sed -re "s/([^^[:space:]])\s+/\1 /g" > asterisk.txt
-    # restore backup of asterisk.tex
-    mv asterisk.tex.orig asterisk.tex
-}
+if ! which wikiexport.py 2>&1 > /dev/null ; then
+	echo
+	echo "wikiexport.py not found in \${PATH}."
+	echo
+	echo "Please add repotools into PATH."
+	echo "    $ svn co http://svn.asterisk.org/svn/repotools"
+	echo
+	exit 1
+fi
 
-VERSION=`cat .version`
-cd doc/tex && make_tex_docs
+if ! which pdftotext 2>&1 > /dev/null ; then
+	echo
+	echo "pdftotext not found.  Please install it."
+	echo
+	echo "On Debian/Ubuntu/Fedora/CentOS, install the poppler-utils package."
+	echo
+	exit 1
+fi
+
+cd doc
+echo "Exporting Asterisk wiki to a PDF (this will take a minute) ..."
+wikiexport.py
+echo "Converting wiki export PDF to plain text ..."
+pdftotext AST.pdf
