update snort: add new files
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@52412 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/snort/configure.in b/src/router/snort/configure.in
--- a/src/router/snort/configure.in
+++ b/src/router/snort/configure.in
@@ -1,11 +1,11 @@
 # $Id$
-AC_INIT
+AC_INIT([snort], [m4_esyscmd_s([cat ./VERSION])])
 AC_CONFIG_SRCDIR([src/snort.c])
 AC_PREREQ(2.50)
 AM_CONFIG_HEADER(config.h)
 # When changing the snort version, please also update the VERSION
 # definition in "src/win32/WIN32-Includes/config.h"
-AM_INIT_AUTOMAKE(snort,2.9.11.1)
+AM_INIT_AUTOMAKE(snort,2.9.20)
 
 NO_OPTIMIZE="no"
 
@@ -66,6 +66,11 @@ case "$host" in
   *-sunos*)
     AC_DEFINE([SUNOS],[1],[Define if SunOS])
     sunos4="yes"
+    ;;
+  *-openwrt*)
+    linux="yes"
+    AC_DEFINE([LINUX],[1],[Define if Linux])
+    AC_SUBST(extra_incl)
     ;;
   *-linux*)
     linux="yes"
@@ -256,7 +261,7 @@ SN_CHECK_DECLS(printf fprintf syslog puts fputs fputc fopen  \
            strcasecmp strncasecmp strerror perror socket sendto   \
            vsnprintf snprintf strtoul)
 
-AC_CHECK_FUNCS([sigaction strlcpy strlcat strerror vswprintf wprintf memrchr inet_ntop])
+AC_CHECK_FUNCS([sigaction strlcpy strlcat strerror vswprintf wprintf memrchr inet_ntop gettid])
 
 AC_CHECK_FUNC([snprintf],[have_snprintf="yes"],[have_snprintf="no"])
 AM_CONDITIONAL(BUILD_SNPRINTF, test "x$have_snprintf" != "xyes")
@@ -570,8 +575,9 @@ AM_CONDITIONAL(SO_WITH_STATIC_LIB, test "x$enable_so_with_static_lib" = "xyes")
 AC_ARG_ENABLE(control_socket,
 [  --enable-control-socket  Enable the control socket],
        enable_control_socket="$enableval", enable_control_socket="no")
+os=`(uname -s)`
 if test "x$linux" != "xyes"; then
-    if test "$OSTYPE" != "FreeBSD"; then
+    if test "$OSTYPE" != "FreeBSD" && "$os" != "FreeBSD"; then
           if test "x$enable_control_socket" = "xyes"; then
              AC_MSG_WARN([[The control socket is only supported on Linux or FreeBSD systems.]])
              enable_control_socket="no"
@@ -587,7 +593,7 @@ AC_ARG_ENABLE(side_channel,
 [  --enable-side-channel    Enable the side channel (Experimental)],
        enable_side_channel="$enableval", enable_side_channel="no")
 if test "x$linux" != "xyes"; then
-    if test "$OSTYPE" != "FreeBSD"; then
+    if test "$OSTYPE" != "FreeBSD" && "$os" != "FreeBSD"; then
        if test "x$enable_side_channel" = "xyes"; then
            AC_MSG_WARN([[The side channel is only supported on Linux or FreeBSD systems.]])
            enable_side_channel="no"
@@ -705,6 +711,22 @@ if test "x$have_daq_decrypted_ssl" = "xyes"; then
         [DAQ version supports decrypted ssl])
 fi
 
+AC_CHECK_DECL([DAQ_PKT_FLAG_LOCALLY_ORIGINATED],
+[have_daq_locally_originated="yes"],
+[have_daq_locally_originated="no"], [#include <daq_common.h>])
+if test "x$have_daq_locally_originated" = "xyes"; then
+    AC_DEFINE([HAVE_DAQ_LOCALLY_ORIGINATED],[1],
+        [DAQ version defines flags for locally originated traffic])
+fi
+
+AC_CHECK_DECL([DAQ_PKT_FLAG_LOCALLY_DESTINED],
+[have_daq_locally_destined="yes"],
+[have_daq_locally_destined="no"], [#include <daq_common.h>])
+if test "x$have_daq_locally_destined" = "xyes"; then
+    AC_DEFINE([HAVE_DAQ_LOCALLY_DESTINED],[1],
+        [DAQ version defines flags for locally destined traffic])
+fi
+
 if test "x$ac_cv_func_daq_dp_add_dc" = "xyes"; then
 
     AC_CHECK_MEMBER([struct _DAQ_DP_key_t.sa.src_ip4],[],[DAQ_C99_STRUCT="no"],[#include <daq_common.h>])
@@ -732,7 +754,7 @@ if test "x$have_daq_flow_id" = "xyes"; then
         [DAQ version supports flow ID in header.])
 fi
 
-have_daq_ext_modflow="no"
+have_daq_ext_modflow="yes"
 AC_MSG_RESULT($have_daq_ext_modflow)
 if test "x$have_daq_ext_modflow" = "xyes"; then
     CCONFIGFLAGS="${CCONFIGFLAGS} -DHAVE_DAQ_EXT_MODFLOW"
@@ -748,7 +770,7 @@ if test "x$have_daq_queryflow" = "xyes"; then
         [DAQ version supports query flow.])
 fi
 
-have_daq_data_channel_flags="no"
+have_daq_data_channel_flags="yes"
 AC_MSG_RESULT($have_daq_data_channel_flags)
 if test "x$have_daq_data_channel_flags" = "xyes"; then
     CCONFIGFLAGS="${CCONFIGFLAGS} -DHAVE_DAQ_DATA_CHANNEL_PARAMS"
@@ -756,7 +778,7 @@ if test "x$have_daq_data_channel_flags" = "xyes"; then
         [DAQ version supports data channel.])
 fi
 
-have_daq_data_channel_separate_ip_versions="no"
+have_daq_data_channel_separate_ip_versions="yes"
 AC_MSG_RESULT($have_daq_data_channel_separate_ip_versions)
 if test "x$have_daq_data_channel_separate_ip_versions" = "xyes"; then
     CCONFIGFLAGS="${CCONFIGFLAGS} -DHAVE_DAQ_DATA_CHANNEL_SEPARATE_IP_VERSIONS"
@@ -865,6 +887,54 @@ AC_ARG_ENABLE(dlclose,
        enable_dlclose="$enableval", enable_dlclose="yes")
 if test "x$enable_dlclose" = "xno"; then
     AC_DEFINE([DISABLE_DLCLOSE_FOR_VALGRIND_TESTING],[1],[Don't close opened shared objects for valgrind leak testing of dynamic libraries])
+fi
+
+##################################################
+# Fedora 28+ does not have inbuilt SunRPC support#
+# in glibc and is separately availble in tirpc   #
+# package. Make sure we've got the library and   #
+# link it                                        #
+##################################################
+
+if test -f /etc/fedora-release ; then
+    DISTRO_VERSION=$(awk '{ print $3 }' /etc/fedora-release)
+    if test $DISTRO_VERSION -ge 28 ; then
+        TIRPC=""
+        AC_CHECK_LIB(tirpc,bindresvport,, TIRPC="no")
+        echo "$TIRPC"
+        if test "x$TIRPC" = "xno"; then
+            echo
+            echo " ERROR! tirpc not found, get it by running "
+            echo " yum install libtirpc-devel "
+            exit
+        fi
+        LIBS="${LIBS} -ltirpc"
+        extra_incl="-I/usr/include/tirpc"
+    fi
+fi
+
+##################################################
+# Centos 8+ does not have inbuilt SunRPC support  #
+# in glibc and is separately availble in tirpc   #
+# package. Make sure we've got the library and   #
+# link it                                        #
+##################################################
+if test -f /etc/centos-release ; then
+    LINUX_FLAVOUR=$(awk '{ print $1 }' /etc/centos-release)
+    DISTRO_VERSION=`cut -d ' ' -f 4 /etc/centos-release | cut -d '.' -f 1`
+    if [[ "$LINUX_FLAVOUR" == "CentOS" ]] && [[ $DISTRO_VERSION -ge 8 ]]; then
+        TIRPC=""
+        AC_CHECK_LIB(tirpc,bindresvport,, TIRPC="no")
+        echo "$TIRPC"
+        if test "x$TIRPC" = "xno"; then
+            echo
+            echo " ERROR! tirpc not found, get it by running "
+            echo " yum install libtirpc-devel or dnf install libtirpc-devel"
+            exit
+        fi
+        LIBS="${LIBS} -ltirpc"
+        extra_incl="-I/usr/include/tirpc"
+    fi
 fi
 
 Z_LIB=""
@@ -993,12 +1063,64 @@ if test "x$enable_inline_init_failopen" = "xyes"; then
     LIBS="$LIBS -lpthread"
 fi
 
+AC_ARG_ENABLE(jemalloc,
+[  --enable-jemalloc Enable jemalloc allocator library],
+       enable_jemalloc="$enableval", enable_jemalloc="no")
+
+AC_ARG_WITH(jemalloc_includes,
+       [  --with-jemalloc-includes=DIR  jemalloc include directory],
+       [with_jemalloc_includes="$withval"],[with_jemalloc_includes="no"])
+
+AC_ARG_WITH(jemalloc_libraries,
+       [  --with-jemalloc-libraries=DIR jemalloc library directory],
+       [with_jemalloc_libraries="$withval"],[with_jemalloc_libraries="no"])
+
+AM_CONDITIONAL(HAVE_JEMALLOC, test "x$enable_jemalloc" = "xyes")
+if test "x$enable_jemalloc" = "xyes"; then
+
+    if test "x$with_jemalloc_includes" != "xno"; then
+        CPPFLAGS="${CPPFLAGS} -I${with_jemalloc_includes}"
+        JEMALLOC_HEADERS="yes"
+    else
+        AC_CHECK_HEADERS(jemalloc.h, JEMALLOC_HEADERS="yes", JEMALLOC_HEADERS="no")
+    fi
+
+    if test "x$with_jemalloc_libraries" != "xno"; then
+        LDFLAGS="${LDFLAGS} -L${with_jemalloc_libraries} -Wl,-rpath,'\$\$ORIGIN/libs/jemalloc',-rpath,'\$\$ORIGIN/jemalloc'"
+        JEMALLOC_LIB="yes"
+    else
+        AC_CHECK_LIB(jemalloc, malloc, JEMALLOC_LIB="yes", JEMALLOC_LIB="no")
+    fi
+
+    if test "x$JEMALLOC_LIB" != "xno"; then
+        if test "x$JEMALLOC_HEADERS" != "xno"; then
+            CPPFLAGS="$CPPFLAGS -DJEMALLOC"
+            LIBS="-ljemalloc $LIBS"
+        fi
+    fi
+
+    if test "x$JEMALLOC_LIB" = "xno"; then
+        echo
+        echo "   ERROR!  jemalloc library not found."
+        echo "   Go get it from http://jemalloc.net/ ." 1>&2; 
+        exit 1; 
+    fi 
+
+    if test "x$JEMALLOC_HEADERS" = "xno"; then
+        echo
+        echo "   ERROR!  jemalloc header not found."
+        echo "   Go get it from http://jemalloc.net/ ." 1>&2; 
+        exit 1; 
+    fi 
+fi 
+
 AC_ARG_ENABLE(pthread,
 [  --disable-pthread        Disable pthread support],
        enable_pthread="$enableval", enable_pthread="yes")
 
 if test "x$enable_pthread" = "xyes"; then
     LIBS="$LIBS -lpthread"
+    AC_CHECK_FUNCS([pthread_tryjoin_np])
 fi
 
 AC_ARG_ENABLE(debug-msgs,
@@ -1193,18 +1315,47 @@ AC_ARG_WITH(intel_soft_cpm_libraries,
 
 if test "x$with_intel_soft_cpm_includes" != "xno"; then
     enable_intel_soft_cpm="yes"
-    CPPFLAGS="${CPPFLAGS} -I${with_intel_soft_cpm_includes}"
 fi
 
 if test "x$with_intel_soft_cpm_libraries" != "xno"; then
     enable_intel_soft_cpm="yes"
-    LDFLAGS="${LDFLAGS} -L${with_intel_soft_cpm_libraries}"
-    LIBS="${LIBS} -lpm"
 fi
 
 AM_CONDITIONAL(HAVE_INTEL_SOFT_CPM, test "x$enable_intel_soft_cpm" = "xyes")
 if test "x$enable_intel_soft_cpm" = "xyes"; then
-    CPPFLAGS="${CPPFLAGS} -DINTEL_SOFT_CPM"
+
+    if test "x$with_intel_soft_cpm_includes" != "xno"; then
+        CPPFLAGS="${CPPFLAGS} -I${with_intel_soft_cpm_includes}"
+        INTEL_SOFT_CPM_HEADERS="yes"
+    else
+        AC_CHECK_HEADERS(cpa.h, INTEL_SOFT_CPM_HEADERS="yes", INTEL_SOFT_CPM_HEADERS="no")
+    fi
+
+    if test "x$with_intel_soft_cpm_libraries" != "xno"; then
+        LDFLAGS="${LDFLAGS} -L${with_intel_soft_cpm_libraries}"
+        INTEL_SOFT_CPM_LIB="yes"
+    else
+        AC_CHECK_LIB(pm, cpaPmPdbAddPattern, INTEL_SOFT_CPM_LIB="yes", INTEL_SOFT_CPM_LIB="no")
+    fi
+
+    if test "x$INTEL_SOFT_CPM_LIB" != "xno"; then
+        if test "x$INTEL_SOFT_CPM_HEADERS" != "xno"; then
+            CPPFLAGS="$CPPFLAGS -DINTEL_SOFT_CPM"
+            LIBS="$LIBS -lpm"
+        fi
+    fi
+
+    if test "x$INTEL_SOFT_CPM_HEADERS" = "xno"; then
+        echo
+        echo "   ERROR!  intel-soft-cpm header not found." 1>&2; 
+        exit 1; 
+    fi
+
+    if test "x$with_intel_soft_cpm_libraries" = "xno"; then
+        echo
+        echo "   ERROR!  intel-soft-cpm library not found." 1>&2; 
+        exit 1;
+    fi
 fi
 
 AC_ARG_ENABLE(shared_rep,
@@ -1253,13 +1404,13 @@ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
 
 ###### Start OpenAppId
 AC_ARG_ENABLE([open-appid],
-    [AS_HELP_STRING([--enable-open-appid ],[Build with application id support. (Experimental)])],
-    [enable_open_appid=$enableval],[enable_open_appid=no])
+    [AS_HELP_STRING([--disable-open-appid],[Disable application identification support.])],
+    [enable_open_appid="$enableval"],[enable_open_appid="yes"])
 
-AM_CONDITIONAL([FEAT_OPEN_APPID],[test x$enable_open_appid = xyes])
+AM_CONDITIONAL([FEAT_OPEN_APPID],[test "x$enable_open_appid" = "xyes"])
 
 if test "x$enable_open_appid" = "xyes"; then
-    AC_DEFINE([FEAT_OPEN_APPID],[1],[Build with application id support. (Experimental)])
+    AC_DEFINE([FEAT_OPEN_APPID],[1],[Build with application identification support.])
     CONFIGFLAGS="$CONFIGFLAGS -DFEAT_OPEN_APPID"
 
     PKG_CHECK_MODULES(luajit, luajit,LLUAJIT="yes",LLUAJIT="no")
@@ -1275,8 +1426,8 @@ if test "x$enable_open_appid" = "xyes"; then
 
     else
         echo
-        echo "   ERROR!  LuaJIT library not found. For better performance, go get it from"
-        echo "   http://www.luajit.org/."
+        echo "   ERROR!  LuaJIT library not found. Go get it from http://www.luajit.org/ (or)"
+        echo "   Try compiling without openAppId using '--disable-open-appid'"
         AC_MSG_ERROR("Fatal!")
     fi
 
@@ -1284,11 +1435,30 @@ if test "x$enable_open_appid" = "xyes"; then
     if test "x$openssl_x509" = "xno"; then
         echo
         echo "   ERROR!  openssl/x509.h or openssl library not found." 
+        echo "   Try compiling without openAppId using '--disable-open-appid'"
         AC_MSG_ERROR("Fatal!")
     fi
 fi
 
 ###### End OpenAppId
+
+#include luajit libs
+
+AC_ARG_WITH(libluajit_includes,
+       [  --with-libluajit-includes=DIR    libluajit include directory],
+       [with_libluajit_includes="$withval"],[with_libluajit_includes="no"])
+
+AC_ARG_WITH(libluajit_libraries,
+       [  --with-libluajit-libraries=DIR   libluajit library directory],
+       [with_libluajit_libraries="$withval"],[with_libluajit_libraries="no"])
+
+if test "x$with_libluajit_includes" != "xno"; then
+    CPPFLAGS="${CPPFLAGS} -I${with_libluajit_includes}"
+fi
+
+if test "x$with_libluajit_libraries" != "xno"; then
+    LDFLAGS="${LDFLAGS}  -L${with_libluajit_libraries}"
+fi
 
 #include nghttp2 libs
 
@@ -1410,6 +1580,22 @@ if test "$ICC" = "no"; then
     CFLAGS="$CFLAGS -Wall"
 fi
 
+AC_MSG_CHECKING(for SFLINUX)
+if test -f /etc/os.conf; then
+    CFLAGS="${CFLAGS} -DSFLINUX"
+    AC_MSG_RESULT(yes)
+else 
+    AC_MSG_RESULT(no)
+fi
+
+AC_MSG_CHECKING(for WRLINUX)
+if test -f /etc/os-release && grep -q "wrlinux" /etc/os-release; then
+    CFLAGS="${CFLAGS} -DWRLINUX"
+    AC_MSG_RESULT(yes)
+else
+    AC_MSG_RESULT(no)
+fi
+
 echo $CFLAGS > cflags.out
 echo $CPPFLAGS > cppflags.out
 
@@ -1458,6 +1644,7 @@ src/dynamic-preprocessors/dns/Makefile \
 src/dynamic-preprocessors/ssl/Makefile \
 src/dynamic-preprocessors/modbus/Makefile \
 src/dynamic-preprocessors/dnp3/Makefile \
+src/dynamic-preprocessors/s7commplus/Makefile \
 src/dynamic-preprocessors/file/Makefile \
 src/dynamic-preprocessors/appid/Makefile \
 src/dynamic-output/Makefile \
