update gnutls (not in use right now): add new files
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@43388 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/gnutls/tests/cert-tests/certtool b/src/router/gnutls/tests/cert-tests/certtool
--- a/src/router/gnutls/tests/cert-tests/certtool
+++ b/src/router/gnutls/tests/cert-tests/certtool
@@ -153,6 +153,18 @@ if test $? = 0;then
 	exit 1
 fi
 
+${VALGRIND} "${CERTTOOL}" -i --infile "${srcdir}/data/commonName.cer" | grep -v "Not After:" > ${TMPFILE1}
+if test $? != 0;then
+	echo "commonName cert output failed"
+	exit 1
+fi
+
+${DIFF} "${srcdir}/data/commonName.cer" ${TMPFILE1}
+if test $? != 0;then
+	exit 1
+fi
+
+
 rm -f ${TMPFILE1} ${TMPFILE2}
 
 export TZ="UTC"
