update boinc: add new files
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@63171 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/boinc/.github/workflows/snap.yml b/src/router/boinc/.github/workflows/snap.yml
--- a/src/router/boinc/.github/workflows/snap.yml
+++ b/src/router/boinc/.github/workflows/snap.yml
@@ -1,6 +1,6 @@
 # This file is part of BOINC.
-# http://boinc.berkeley.edu
-# Copyright (C) 2023 University of California
+# https://boinc.berkeley.edu
+# Copyright (C) 2025 University of California
 #
 # BOINC is free software; you can redistribute it and/or modify it
 # under the terms of the GNU Lesser General Public License
@@ -18,12 +18,12 @@
 name: Snap
 on:
   push:
-    branches: [ master, 'client_release/**' ]
+    branches: [ master ]
     tags: [ 'client_release/**' ]
   pull_request:
     branches: [ master ]
   schedule:
-    - cron:  '0 0 * * *'
+    - cron: '0 0 * * *'
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
@@ -47,11 +47,11 @@ jobs:
           snap_file: boinc_amd64.snap
 
     steps:
-    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
+    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
 
     - name: Install dependencies
       run: |
-        sudo apt-get -qq update
+        sudo apt-get update
         sudo apt-get install -y p7zip-full
 
     - name: Running from origin repo
@@ -64,9 +64,19 @@ jobs:
       run: |
         echo "VCPKG_BINARY_SOURCES=clear;x-aws-config,no-sign-request;x-aws,s3://vcpkg.cache.boinc/,read" >> $GITHUB_ENV
 
+    - name: Fix version in the snapcraft.yaml
+      run: |
+        PKG_VERSION=$(cat version.h | grep BOINC_VERSION_STRING | sed -e 's|#define BOINC_VERSION_STRING||' | jq -r .)
+        if [[ "x${PKG_VERSION}" == "x" ]]; then
+          printf "Could not obtain release package version from version.h"
+          exit 1
+        fi
+        PKG_VERSION_FULL="${PKG_VERSION}-${{ github.run_number }}"
+        sed -i -E "s/(version: \"$PKG_VERSION\")/version: \"$PKG_VERSION_FULL\"/" ${{ github.workspace }}/snap/snapcraft.yaml
+
     - name: Configure docker qemu
       if: success()
-      uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee
+      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130
 
     - name: Build boinc snap
       if: success()
@@ -98,12 +108,12 @@ jobs:
           --workdir /root \
           --platform "${{ matrix.architecture }}" \
           diddledani/snapcraft:core22 \
-          "snap install --devmode ${{ matrix.snap_file }} && boinc --version && boinc.client --version"
+          "snap install --dangerous ${{ matrix.snap_file }} && boinc --version && boinc.client --version"
 
     - name: Install and test snap boinc x64
       if: success() && matrix.type == 'x64'
       run: |
-        sudo snap install --devmode ${{ matrix.snap_file }}
+        sudo snap install --dangerous ${{ matrix.snap_file }}
         boinc --version
         boinc.client --version
 
@@ -115,18 +125,32 @@ jobs:
 
     - name: Upload logs on failure
       if: ${{ failure() }}
-      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b
+      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
       with:
         name: snap_logs_${{ matrix.type }}_${{ github.event.pull_request.head.sha }}
         path: deploy/logs.7z
 
-    - name: Prepare artifacts for deploy
-      if: success()
-      run: python ./deploy/prepare_deployment.py linux_snap
+    - name: Publish nightly snap build to the edge
+      if: success() && matrix.type == 'x64' && github.ref == 'refs/heads/master' && github.event_name == 'schedule'
+      uses: canonical/action-publish@214b86e5ca036ead1668c79afb81e550e6c54d40
+      env:
+        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_LOGIN }}
+      with:
+        snap: ${{ matrix.snap_file }}
+        release: edge
+
+    - name: Publish alpha snap build to the beta
+      if: success() && matrix.type == 'x64' && startsWith(github.ref, 'refs/tags/')
+      uses: canonical/action-publish@214b86e5ca036ead1668c79afb81e550e6c54d40
+      env:
+        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_LOGIN }}
+      with:
+        snap: ${{ matrix.snap_file }}
+        release: beta
 
     - name: Upload artifacts
-      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b
+      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
       if: success()
       with:
         name: linux_snap_${{ matrix.type }}_${{ github.event.pull_request.head.sha }}
-        path: deploy/linux_snap.7z
+        path: boinc_*.snap
