update quagga
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@31639 52c4871e-980c-0410-b1e0-e73912ce01f8

Former-commit-id: c994ed4de429b722788e69ad071167bdecae8597

diff --git a/src/router/quagga/solaris/quagga.init.in b/src/router/quagga/solaris/quagga.init.in
--- a/src/router/quagga/solaris/quagga.init.in
+++ b/src/router/quagga/solaris/quagga.init.in
@@ -120,7 +120,7 @@ routeadm_daemon_args () {
 	
 	# user and group we need for config file upgrade..
 	SMF_USER=`get_routeadm_property $SMF_FMRI user`
-	SMF_GROUP=`get_routeadm_property()$SMF_FMRI group`
+	SMF_GROUP=`get_routeadm_property() $SMF_FMRI group`
 	if [ "${SMF_USER}" ] ; then
 		USER="${SMF_USER}"
 		args="${args} -u ${SMF_USER}"
@@ -197,7 +197,7 @@ fi
 DAEMON="$1"
 
 # daemon path must be given
-if [ -z "$DAEMON_PATH/$DAEMON" ]; then
+if [ "$DAEMON_PATH/$DAEMON" = "/" ]; then
 	usage
 	exit $SMF_EXIT_ERR_FATAL
 fi
@@ -231,9 +231,13 @@ fi
 
 upgrade_config "$DAEMON"
 
-if [ ! -f "@sysconfdir@/${DAEMON}.conf" ] ; then
-	echo "Could not find config file, @sysconfdir@/${DAEMON}.conf"
-	exit $SMF_EXIT_ERR_CONFIG
+CONF_FILE=`get_routeadm_property $SMF_FMRI config_file`
+if [ -z "$CONF_FILE" ] ; then
+        CONF_FILE="@sysconfdir@/${DAEMON}.conf"
+fi
+if [ ! -f "$CONF_FILE" ] ; then
+        echo "Could not find config file, $CONF_FILE"
+        exit $SMF_EXIT_ERR_CONFIG
 fi
 
 # we need @quagga_statedir@ to exist, it probably is on tmpfs.
