update wolfssl: add new files
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@59405 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/wolfssl/.github/workflows/cyrus-sasl.yml b/src/router/wolfssl/.github/workflows/cyrus-sasl.yml
--- a/src/router/wolfssl/.github/workflows/cyrus-sasl.yml
+++ b/src/router/wolfssl/.github/workflows/cyrus-sasl.yml
@@ -15,8 +15,9 @@ concurrency:
 jobs:
   build_wolfssl:
     name: Build wolfSSL
+    if: github.repository_owner == 'wolfssl'
     # Just to keep it the same as the testing target
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     # This should be a safe limit for the tests to run.
     timeout-minutes: 4
     steps:
@@ -29,11 +30,14 @@ jobs:
           # Don't run tests as this config is tested in many other places
           check: false
 
+      - name: tar build-dir
+        run: tar -zcf build-dir.tgz build-dir
+
       - name: Upload built lib
         uses: actions/upload-artifact@v4
         with:
           name: wolf-install-sasl
-          path: build-dir
+          path: build-dir.tgz
           retention-days: 5
 
   sasl_check:
@@ -43,7 +47,8 @@ jobs:
         # List of releases to test
         ref: [ 2.1.28 ]
     name: ${{ matrix.ref }}
-    runs-on: ubuntu-latest
+    if: github.repository_owner == 'wolfssl'
+    runs-on: ubuntu-22.04
     # This should be a safe limit for the tests to run.
     timeout-minutes: 4
     needs: build_wolfssl
@@ -60,7 +65,9 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: wolf-install-sasl
-          path: build-dir
+
+      - name: untar build-dir
+        run: tar -xf build-dir.tgz
 
       - name: Checkout OSP
         uses: actions/checkout@v4
@@ -88,4 +95,11 @@ jobs:
         working-directory: sasl
         run: |
           make -j -C utils testsuite saslpasswd2
-          $GITHUB_WORKSPACE/osp/cyrus-sasl/${{ matrix.ref }}/run-tests.sh
+          # Retry up to five times
+          for i in {1..5}; do
+             TEST_RES=0
+             $GITHUB_WORKSPACE/osp/cyrus-sasl/${{ matrix.ref }}/run-tests.sh || TEST_RES=$?
+             if [ "$TEST_RES" -eq "0" ]; then
+                break
+             fi
+          done
