update wolfssl: add new files
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@55291 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/wolfssl/.github/workflows/hostap.yml b/src/router/wolfssl/.github/workflows/hostap.yml
--- a/src/router/wolfssl/.github/workflows/hostap.yml
+++ b/src/router/wolfssl/.github/workflows/hostap.yml
@@ -4,6 +4,48 @@ on:
   workflow_call:
 
 jobs:
+  build_wolfssl:
+    strategy:
+      matrix:
+        include:
+          - build_id: hostap-build1
+            wolf_extra_config: --disable-tls13
+          - build_id: hostap-build2
+            wolf_extra_config: --enable-brainpool --enable-wpas-dpp
+    name: Build wolfSSL
+    # Just to keep it the same as the testing target
+    runs-on: ubuntu-20.04
+    # This should be a safe limit for the tests to run.
+    timeout-minutes: 4
+    steps:
+        # No way to view the full strategy in the browser (really weird)
+      - name: Print strategy
+        run: |
+          cat <<EOF
+          ${{ toJSON(matrix) }}
+          EOF
+
+      - if: ${{ runner.debug }}
+        name: Enable wolfSSL debug logging
+        run: |
+          echo "wolf_debug_flags=--enable-debug" >> $GITHUB_ENV
+
+      - name: Build wolfSSL
+        uses: wolfSSL/actions-build-autotools-project@v1
+        with:
+          path: wolfssl
+          configure: >-
+            --enable-wpas CFLAGS=-DWOLFSSL_STATIC_RSA
+            ${{ env.wolf_debug_flags }} ${{ matrix.wolf_extra_config }}
+          install: true
+
+      - name: Upload built lib
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ matrix.build_id }}
+          path: build-dir
+          retention-days: 1
+
   # Build wpa_supplicant with wolfSSL and hostapd with OpenSSL and interop.
   hostap_test:
     strategy:
@@ -20,16 +62,17 @@ jobs:
         config: [
           {
             hostap_ref: hostap_2_10,
-            hostap_cherry_pick: 698c05da2bd3233b005d45873caa852bc29b32c5,
+            hostap_cherry_pick: 5679ec5c3dda25a0547a5f66407fd9b0b55fd04a,
             remove_teap: true,
             # TLS 1.3 does not work for this version
-            wolf_extra_config: --disable-tls13,
+            build_id: hostap-build1,
           },
           # Test the dpp patch
           {
             hostap_ref: b607d2723e927a3446d89aed813f1aa6068186bb,
+            hostap_cherry_pick: 5679ec5c3dda25a0547a5f66407fd9b0b55fd04a,
             osp_ref: ad5b52a49b3cc2a5bfb47ccc1d6a5137132e9446,
-            wolf_extra_config: --enable-brainpool --enable-wpas-dpp
+            build_id: hostap-build2
           },
         ]
         # parallelize the tests to be able to run all tests within 10 minutes
@@ -44,11 +87,14 @@ jobs:
             config: {
               hostap_ref: b607d2723e927a3446d89aed813f1aa6068186bb,
               osp_ref: ad5b52a49b3cc2a5bfb47ccc1d6a5137132e9446,
-              wolf_extra_config: --enable-brainpool --enable-wpas-dpp
+              build_id: hostap-build2
             }
     name: hwsim test
     # For openssl 1.1
     runs-on: ubuntu-20.04
+    # This should be a safe limit for the tests to run.
+    timeout-minutes: 12
+    needs: build_wolfssl
     steps:
         # No way to view the full strategy in the browser (really weird)
       - name: Print strategy
@@ -56,6 +102,20 @@ jobs:
           cat <<EOF
           ${{ toJSON(matrix) }}
           EOF
+
+      - name: Print computed job run ID
+        run: |
+          SHA_SUM=$(sha256sum << 'END_OF_HEREDOC' | cut -d " " -f 1
+          ${{ toJSON(github) }}
+          END_OF_HEREDOC
+          )
+          echo "our_job_run_id=$SHA_SUM" >> $GITHUB_ENV
+          echo Our job run ID is $SHA_SUM
+
+      - name: Checkout wolfSSL
+        uses: actions/checkout@v3
+        with:
+          path: wolfssl
 
       - name: Install dependencies
         run: |
@@ -75,19 +135,15 @@ jobs:
           lsmod | grep mac80211
 
       - if: ${{ runner.debug }}
-        name: Enable wolfSSL and hostap debug logging
+        name: Enable hostap debug logging
         run: |
-          echo "wolf_debug_flags=--enable-debug" >> $GITHUB_ENV
           echo "hostap_debug_flags=-d" >> $GITHUB_ENV
 
-      - name: Build wolfSSL
-        uses: wolfSSL/actions-build-autotools-project@v1
+      - name: Download lib
+        uses: actions/download-artifact@v3
         with:
-          path: wolfssl
-          configure: >-
-            --enable-wpas CFLAGS=-DWOLFSSL_STATIC_RSA
-            ${{ env.wolf_debug_flags }} ${{ matrix.config.wolf_extra_config }}
-          install: true
+          name: ${{ matrix.config.build_id }}
+          path: build-dir
 
       - name: Setup d-bus
         working-directory: wolfssl/.github/workflows/hostap-files
@@ -125,7 +181,7 @@ jobs:
       - if: ${{ matrix.config.hostap_cherry_pick }}
         name: Cherry pick certificate update
         working-directory: hostap
-        run: git cherry-pick -n ${{ matrix.config.hostap_cherry_pick }}
+        run: git cherry-pick -n -X theirs ${{ matrix.config.hostap_cherry_pick }}
 
       - if: ${{ matrix.config.osp_ref }}
         name: Checkout OSP
@@ -189,12 +245,25 @@ jobs:
         id: testing
         working-directory: hostap/tests/hwsim/
         run: |
-          # Run tests in increments of 100 to cut down on the uploaded log size.
-          while mapfile -t -n 100 ary && ((${#ary[@]})); do
+          # Run tests in increments of 50 to cut down on the uploaded log size.
+          while mapfile -t -n 50 ary && ((${#ary[@]})); do
             TESTS=$(printf '%s\n' "${ary[@]}" | tr '\n' ' ')
-            sudo ./start.sh
-            sudo ./run-tests.py ${{ env.hostap_debug_flags }} --split ${{ matrix.server }}/5 $TESTS
-            sudo ./stop.sh
+            # Retry up to three times
+            for i in {1..3}; do
+              HWSIM_RES=0 # Not set when command succeeds
+              # Logs can grow quickly especially in debug mode
+              sudo rm -rf logs
+              sudo ./start.sh
+              sudo ./run-tests.py ${{ env.hostap_debug_flags }} --split ${{ matrix.server }}/5 $TESTS || HWSIM_RES=$?
+              sudo ./stop.sh
+              if [ "$HWSIM_RES" -eq "0" ]; then
+                break
+              fi
+            done
+            echo "test ran $i times"
+            if [ "$HWSIM_RES" -ne "0" ]; then
+              exit $HWSIM_RES
+            fi
           done < $GITHUB_WORKSPACE/wolfssl/.github/workflows/hostap-files/configs/${{ matrix.config.hostap_ref }}/tests
 
       - name: Change failure log permissions
@@ -208,7 +277,7 @@ jobs:
         if: ${{ failure() && steps.testing.outcome == 'failure' }}
         uses: actions/upload-artifact@v3
         with:
-          name: hostap-logs
+          name: hostap-logs-${{ env.our_job_run_id }}
           path: hostap/tests/hwsim/logs.zip
           retention-days: 5
 
