update util-linux: add new files
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@51753 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/util-linux/Makefile.am b/src/router/util-linux/Makefile.am
--- a/src/router/util-linux/Makefile.am
+++ b/src/router/util-linux/Makefile.am
@@ -2,20 +2,31 @@ AM_CPPFLAGS = \
 	-include config.h \
 	-I$(top_srcdir)/include \
 	-DLOCALEDIR=\"$(localedir)\" \
-	-D_PATH_LOCALSTATEDIR=\"${localstatedir}\"
+	-D_PATH_RUNSTATEDIR=\"${runstatedir}\" \
+	-D_PATH_SYSCONFSTATICDIR=\"${sysconfstaticdir}\"
+
+if USE_VENDORDIR
+AM_CPPFLAGS += \
+	-D_PATH_VENDORDIR=\"${vendordir}\"
+endif
+
+if FUZZING_ENGINE
+if !OSS_FUZZ
+AM_CPPFLAGS += \
+	-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
+endif
+endif
+
 AM_CFLAGS = -fsigned-char $(WARN_CFLAGS)
-AM_LDFLAGS =
+AM_CXXFLAGS = $(AM_CFLAGS)
+AM_LDFLAGS = $(ASAN_LDFLAGS) $(UBSAN_LDFLAGS) $(FUZZING_ENGINE_LDFLAGS)
 
 # Add gettext stuff to the global LDADD for systems with separate libintl
 # library. The LTLIBINTL is generated by AM_GNU_GETTEXT macro.
 #
 LDADD = $(LTLIBINTL)
 
-# Automake (at least up to 1.10) mishandles dist_man_MANS inside conditionals.
-# Unlike with other dist primaries, the files are not distributed if the
-# conditional is false.
-# Work the bug around until it is fixed:
-dist_noinst_DATA = $(dist_man_MANS)
+LIB_FUZZING_ENGINE ?= -fsanitize=fuzzer
 
 # Paths to in-tree libraries (use ul_ prefix to avoid possible collisions) Note
 # that blkid.h, libmount.h, libfdisk.h and libsmartcols.h are generated and
@@ -28,16 +39,14 @@ ul_libfdisk_incdir  = $(top_builddir)/libfdisk/src
 
 ul_libuuid_incdir  = $(top_srcdir)/libuuid/src
 
-pkgconfigdir = $(usrlib_execdir)/pkgconfig
-
 bashcompletiondir = @bashcompletiondir@
 
 dist_noinst_HEADERS =
+dist_noinst_DATA =
 noinst_PROGRAMS =
-noinst_LTLIBRARIES =
+EXTRA_LTLIBRARIES =
 usrbin_exec_PROGRAMS =
 usrsbin_exec_PROGRAMS =
-dist_man_MANS =
 man_MANS =
 pkgconfig_DATA =
 usrlib_exec_LTLIBRARIES =
@@ -48,9 +57,11 @@ systemdsystemunit_DATA =
 dist_bashcompletion_DATA =
 check_PROGRAMS =
 dist_check_SCRIPTS =
-TESTS =
 
 PATHFILES =
+ADOCFILES_COMMON =
+MANPAGES =
+MANLINKS =
 
 INSTALL_EXEC_HOOKS =
 UNINSTALL_HOOKS =
@@ -63,6 +74,12 @@ CLEANFILES =
 
 SUBDIRS = po
 
+if ENABLE_ASCIIDOC
+if ENABLE_POMAN
+SUBDIRS += po-man
+endif
+endif
+
 RCS_FIND_IGNORE = \( -name SCCS -o -name BitKeeper -o -name .svn -o \
 		-name CVS -o -name .pc -o -name .hg -o -name .git \) -prune -o
 
@@ -73,10 +90,9 @@ EXTRA_DIST += \
 	autogen.sh \
 	Documentation \
 	po/update-potfiles \
-	README.licensing \
-	tools/git-version-gen
+	README.licensing
 
-
+include tools/Makemodule.am
 include include/Makemodule.am
 include lib/Makemodule.am
 include libuuid/Makemodule.am
@@ -94,8 +110,40 @@ include misc-utils/Makemodule.am
 include disk-utils/Makemodule.am
 
 include bash-completion/Makemodule.am
+include man-common/Makemodule.am
 
 include tests/Makemodule.am
+
+# Meson files
+EXTRA_DIST += \
+	meson.build \
+	meson_options.txt \
+	tools/meson-make-manpage-stub.sh \
+	tools/meson-make-symlink.sh \
+	\
+	include/meson.build \
+	libblkid/meson.build \
+	libmount/meson.build \
+	libmount/python/meson.build \
+	misc-utils/meson.build \
+	libsmartcols/meson.build \
+	text-utils/meson.build \
+	po/meson.build \
+	lib/meson.build \
+	libuuid/meson.build \
+	sys-utils/meson.build \
+	libfdisk/meson.build \
+	term-utils/meson.build \
+	disk-utils/meson.build \
+	login-utils/meson.build
+
+# pylibmountexec module must be installed after usrlib_exec libraries,
+# otherwise the libtool relink step will fail to find libmount.la and
+# will try -lmount which is possibly not available.
+#
+# So introduce this dependency rule:
+# install-pylibmountexecLTLIBRARIES: install-usrlib_execLTLIBRARIES
+@verbatim_pylibmount_dependency@
 
 #
 # Don't rely on configure.ac AC_CONFIG_FILES for install paths.
@@ -112,8 +160,9 @@ edit_cmd = sed \
 	 -e 's|@datadir[@]|$(datadir)|g' \
 	 -e 's|@sbindir[@]|$(sbindir)|g' \
 	 -e 's|@bindir[@]|$(bindir)|g' \
+	 -e 's|@docdir[@]|$(docdir)|g' \
 	 -e 's|@includedir[@]|$(includedir)|g' \
-	 -e 's|@localstatedir[@]|$(localstatedir)|g' \
+	 -e 's|@runstatedir[@]|$(runstatedir)|g' \
 	 -e 's|@usrlib_execdir[@]|$(usrlib_execdir)|g' \
 	 -e 's|@usrbin_execdir[@]|$(usrbin_execdir)|g' \
 	 -e 's|@usrsbin_execdir[@]|$(usrsbin_execdir)|g' \
@@ -132,23 +181,96 @@ edit_cmd = sed \
 	 -e 's|@LIBFDISK_PATCH_VERSION[@]|$(LIBFDISK_PATCH_VERSION)|g' \
 	 -e 's|@LIBBLKID_VERSION[@]|$(LIBBLKID_VERSION)|g'
 
-CLEANFILES += $(PATHFILES)
+if HAVE_SELINUX
+edit_cmd += -e 's|@LIBSELINUX[@]|libselinux|g'
+else
+edit_cmd += -e 's|@LIBSELINUX[@]||g'
+endif
+
+if HAVE_CRYPTSETUP
+if CRYPTSETUP_VIA_DLOPEN
+edit_cmd += -e 's|@LIBCRYPTSETUP[@]||g'
+edit_cmd += -e 's|@LIBDL[@]|-ldl|g'
+else
+edit_cmd += -e 's|@LIBCRYPTSETUP[@]|libcryptsetup|g'
+edit_cmd += -e 's|@LIBDL[@]||g'
+endif
+else
+edit_cmd += -e 's|@LIBCRYPTSETUP[@]||g'
+edit_cmd += -e 's|@LIBDL[@]||g'
+endif
+
+if USE_VENDORDIR
+edit_cmd += -e 's|@vendordir[@]|$(vendordir)|g'
+else
+edit_cmd += -e 's|@vendordir[@]||g'
+endif
+
+CLEANFILES += $(PATHFILES) $(EXTRA_LTLIBRARIES)
 EXTRA_DIST += $(PATHFILES:=.in)
 
 $(PATHFILES): Makefile
 	@ rm -f $@ $@.tmp
-	$(AM_V_at) test -d $(dir $@) || mkdir -p $(dir $@)
+	$(AM_V_at) $(MKDIR_P) $$(dirname $@)
 	$(AM_V_GEN) srcdir=''; \
 		test -f ./$@.in || srcdir=$(srcdir)/; \
 		$(edit_cmd) $${srcdir}$@.in >$@.tmp
 	@ mv $@.tmp $@
 
+
+if ENABLE_ASCIIDOC
+EXTRA_DIST += $(ADOCFILES_COMMON) $(MANPAGES) $(MANLINKS)
+man_MANS += $(MANPAGES) $(MANLINKS)
+
+$(MANPAGES): $(ADOCFILES_COMMON)
+
+asciidoc_man_cmd = $(ASCIIDOCTOR) \
+	-b manpage \
+	-a 'release-version=$(VERSION)' \
+	-a 'package-docdir=$(docdir)' \
+	-a 'VERSION=$(VERSION)' \
+	-a 'ADJTIME_PATH=$(ADJTIME_PATH)'
+
+SUFFIXES = .1.adoc .3.adoc .5.adoc .8.adoc .1 .3 .5 .8
+.1.adoc.1 .3.adoc.3 .5.adoc.5 .8.adoc.8:
+	$(AM_V_GEN) test -f ./$@ || \
+		$(MKDIR_P) $$(dirname $@) && \
+		$(asciidoc_man_cmd) --base-dir=$(abs_srcdir) \
+				    --destination-dir $(abs_builddir)/$$(dirname $@) $<
+
+$(MANLINKS): $(MANPAGES)
+gen-man: $(man_MANS)
+
+# Standard "make" follows BUILD_* macros from ./configure, and in this case, it
+# ignores man pages for disabled tools, but for distribution tarball, we need
+# to generate all man-pages (to avoid dependence on asciidoc). [kzak Jan-2022]
+gen-man-dist:
+	@list=`find -name *.adoc -not -path "*/man-common/*" -not -path "*/po-man/*" | sed -e 's/\.adoc//g'`; \
+	missing=`for p in $$list; do test -f $$p || echo $$p; done`; \
+	if test -n "$$missing"; then \
+		$(MAKE) $(AM_MAKEFLAGS) $$missing; \
+	fi;
+
+
+# !ENABLE_ASCIIDOC
+else
+
+if HAVE_MANPAGES
+EXTRA_DIST += $(ADOCFILES_COMMON) $(MANPAGES) $(MANLINKS)
+man_MANS += $(MANPAGES) $(MANLINKS)
+endif
+
+gen-man:
+gen-man-dist:
+endif
+
+
 # Arrange so that .tarball-version appears only in the distribution
 # tarball, and never in a checked-out repository.
-dist-hook:
+dist-hook: gen-man-dist
 	echo $(VERSION) > $(distdir)/.tarball-version
 # Set ChangeLog tag reference.
-	sed -i "s/log/log;h=$(VERSION)/" $(distdir)/ChangeLog
+	sed -i "s!log!log?h=v$(VERSION)!" $(distdir)/ChangeLog
 
 distclean-local:
 	-find . -name \*~ -o -name \*.orig -o -name \*.rej | xargs rm -f
@@ -166,7 +288,8 @@ checkconfig:
 		| xargs $(top_srcdir)/tools/checkconfig.sh $(top_srcdir)
 
 checkmans:
-	@$(top_srcdir)/tools/checkmans.sh
+	@$(top_srcdir)/tools/checkadoc-missing.sh
+	@$(top_srcdir)/tools/checkadoc-repeat.sh
 
 checkxalloc:
 	@ $(top_srcdir)/tools/checkxalloc.sh
@@ -174,15 +297,38 @@ checkxalloc:
 checkdecl:
 	@ $(top_srcdir)/tools/checkdecl.sh
 
+checkcompletion:
+	@ $(top_srcdir)/tools/checkcompletion.sh $(top_srcdir)
+
+checkusage:
+	@ $(top_srcdir)/tools/checkusage.sh \
+		$(bin_PROGRAMS) $(sbin_PROGRAMS) \
+		$(usrbin_exec_PROGRAMS) $(usrsbin_exec_PROGRAMS)
+checklibdoc:
+	@ $(top_srcdir)/tools/checklibdocs.sh \
+		$(top_srcdir)/libmount/src/libmount.sym \
+		$(top_srcdir)/libmount/docs/libmount-sections.txt
+	@ $(top_srcdir)/tools/checklibdocs.sh \
+		$(top_srcdir)/libfdisk/src/libfdisk.sym \
+		$(top_srcdir)/libfdisk/docs/libfdisk-sections.txt
+	@ $(top_srcdir)/tools/checklibdocs.sh \
+		$(top_srcdir)/libsmartcols/src/libsmartcols.sym \
+		$(top_srcdir)/libsmartcols/docs/libsmartcols-sections.txt
+	@ $(top_srcdir)/tools/checklibdocs.sh \
+		$(top_srcdir)/libblkid/src/libblkid.sym \
+		$(top_srcdir)/libblkid/docs/libblkid-sections.txt
+
 DISTCHECK_CONFIGURE_FLAGS = \
+	--disable-makeinstall-chown \
 	--disable-use-tty-group \
 	--disable-silent-rules \
+	--disable-rpath \
 	--enable-all-programs \
-	--enable-static-programs \
 	--enable-gtk-doc \
 	--with-python \
 	--with-bashcompletiondir=$$dc_install_base/$(bashcompletiondir) \
 	--with-systemdsystemunitdir=$$dc_install_base/$(systemdsystemunitdir)
+
 
 BUILT_SOURCES = .version
 .version:
@@ -205,6 +351,8 @@ $(CHANGELOG_FILE):
 #
 checksmatch:
 	$(MAKE) CHECK="smatch --data=$(abs_top_srcdir)/tools/smatch-data" CC=cgcc
+
+check-programs: $(check_PROGRAMS)
 
 changelog: $(CHANGELOG_FILE)
 
diff --git a/src/router/util-linux/tests/ts/misc/setarch b/src/router/util-linux/tests/ts/misc/setarch
--- a/src/router/util-linux/tests/ts/misc/setarch
+++ b/src/router/util-linux/tests/ts/misc/setarch
@@ -20,6 +20,73 @@ ts_init "$*"
 
 ts_check_test_command "$TS_CMD_SETARCH"
 
-$TS_CMD_SETARCH $(uname -m) -vRFZLXBIST3 --uname-2.6 echo "success" >$TS_OUTPUT 2>&1
+ARCH=$(uname -m)
+
+ts_init_subtest options
+test -e /.dockerenv && ts_skip "unsupported in docker environment"
+ts_log_both "###### unknown arch"
+$TS_CMD_SETARCH qubit -v echo "success" >> $TS_OUTPUT 2>> $TS_ERRLOG
+echo "exit: $?" >>$TS_OUTPUT
+
+ts_log_both "###### unknown command"
+$TS_CMD_SETARCH $ARCH -v /das/gibs/nicht >> $TS_OUTPUT 2>> $TS_ERRLOG
+echo "exit: $?" >>$TS_OUTPUT
+
+echo "###### noop uname -a" >>$TS_OUTPUT
+uname_a=$(uname -srm)
+$TS_CMD_SETARCH $ARCH -v uname -srm >> $TS_OUTPUT 2>> $TS_ERRLOG
+sed -i "$ s@${uname_a}@uname -a unchanged@" $TS_OUTPUT
+
+echo "###### almost all options" >>$TS_OUTPUT
+$TS_CMD_SETARCH $ARCH -vRFZLXBIST3 echo "success" >> $TS_OUTPUT 2>> $TS_ERRLOG
+ts_finalize_subtest
+
+
+ts_init_subtest uname26
+finmsg="" # for debugging 2.6 issues
+
+echo "###### --uname-2.6 echo" >>$TS_OUTPUT
+$TS_CMD_SETARCH $ARCH -v --uname-2.6 echo "2.6 worked" >> $TS_OUTPUT 2>&1
+if [ $? -eq 0 ]; then
+	expected='^2.6 worked$'
+else
+	# this may happen after execvp - gets written to stderr
+	expected="^FATAL: kernel too old$"
+	finmsg+=" echo"
+fi
+sed -i "$ s/$expected/2.6 works or kernel too old/" $TS_OUTPUT
+
+echo "###### --uname-2.6 true, non-verbose" >>$TS_OUTPUT
+$TS_CMD_SETARCH $ARCH --uname-2.6 true >> $TS_OUTPUT 2>&1
+if [ $? -eq 0 ]; then
+	echo "2.6 works or kernel too old" >> $TS_OUTPUT
+else
+	# this may happen after execvp - gets written to stderr
+	expected="^FATAL: kernel too old$"
+	sed -i "$ s/$expected/2.6 works or kernel too old/" $TS_OUTPUT
+	finmsg+=" true"
+fi
+
+if [ -n "$finmsg" ]; then
+	finmsg=$(echo unsupported --uname-2.6: $finmsg)
+else
+	uname26_seems_supported=yes
+fi
+ts_finalize_subtest "$finmsg"
+
+
+# conditional subtest
+if [ "$uname26_seems_supported" = "yes" ]; then
+ts_init_subtest uname26-version
+	tmp=$($TS_CMD_SETARCH $ARCH --uname-2.6 uname -r)
+	if echo "$tmp" | grep -q "^2\.6\."; then
+		echo "kernel version changed to 2.6" >> $TS_OUTPUT
+	else
+		echo "uname26 failed" >> $TS_OUTPUT
+		echo "original kernel: $(uname -r)" >> $TS_OUTPUT
+		echo "uname26 kernel:  $tmp" >> $TS_OUTPUT
+	fi
+ts_finalize_subtest
+fi # conditional subtest
 
 ts_finalize
diff --git a/src/router/util-linux/tests/ts/mount/move b/src/router/util-linux/tests/ts/mount/move
--- a/src/router/util-linux/tests/ts/mount/move
+++ b/src/router/util-linux/tests/ts/mount/move
@@ -24,47 +24,70 @@ ts_init "$*"
 ts_check_test_command "$TS_CMD_MOUNT"
 ts_check_test_command "$TS_CMD_UMOUNT"
 ts_check_test_command "$TS_CMD_FINDMNT"
+ts_check_test_command "$TS_CMD_MOUNTPOINT"
 
 ts_skip_nonroot
 
-DIR_PRIVATE2="$TS_OUTDIR/mnt-move-private2"
+function mount_and_check {
+	# last arg must be an existing or to-be-mounted mountpoint
+	local mountpoint="${@: -1}"
+
+	$TS_CMD_MOUNT "$@" \
+		|| ts_die "error: mount $*"
+
+	$TS_CMD_MOUNTPOINT -q "$mountpoint" \
+		|| ts_die "error: mountpoint $mountpoint"
+}
+
 DIR_PRIVATE="$TS_OUTDIR/mnt-move-private"
 
 DIR_SRC="$DIR_PRIVATE/mnt-move-src"
 DIR_A="$DIR_PRIVATE/mnt-move-A"
 DIR_B="$DIR_PRIVATE/mnt-move-B"
 
+# this may fail if there are mounted dirs left
+rm -rf "$DIR_PRIVATE" || ts_die "cleanup failed, check manually!"
+mkdir "$DIR_PRIVATE"  || ts_die "error: mkdir DIR_PRIVATE"
+
 # create bind mount and make it private to be sure
 # (kernel cannot move mount with shared parent)
-[ -d $DIR_PRIVATE2 ] || mkdir $DIR_PRIVATE2
-[ -d $DIR_PRIVATE ] || mkdir $DIR_PRIVATE
-$TS_CMD_MOUNT --bind $DIR_PRIVATE2 $DIR_PRIVATE
-$TS_CMD_MOUNT --make-private $DIR_PRIVATE
+mount_and_check --bind $DIR_PRIVATE $DIR_PRIVATE
+mount_and_check --make-rprivate $DIR_PRIVATE
 
-[ -d $DIR_SRC ] || mkdir $DIR_SRC
-[ -d $DIR_A ] || mkdir $DIR_A
-[ -d $DIR_B ] || mkdir $DIR_B
+# Is the bind mount still rw?
+mkdir $DIR_SRC $DIR_A $DIR_B \
+	|| ts_die "error: mkdir on private bind mount"
 
 # bind
-$TS_CMD_MOUNT --bind $DIR_SRC $DIR_A
-
-# check the bind
-$TS_CMD_FINDMNT --kernel --target "$DIR_A" &> /dev/null
-[ "$?" == "0" ] || ts_die "Cannot find binded $DIR_A in /proc/self/mountinfo"
+mount_and_check --bind $DIR_SRC $DIR_A
 
 # move
-$TS_CMD_MOUNT --move $DIR_A $DIR_B
+mount_and_check --move $DIR_A $DIR_B
 
-# check the move
-$TS_CMD_FINDMNT --kernel --target "$DIR_B" &> /dev/null
-[ "$?" == "0" ] || ts_die "Cannot find binded $DIR_B in /proc/self/mountinfo"
+# BTW a basic test for findmnt(8) and mountpoint(1)
+for f in `find $DIR_PRIVATE2 $DIR_PRIVATE`; do
+	xo="$($TS_CMD_MOUNTPOINT -q "$f" 2>&1)"
+	x=$?
+	# mountpoint(1) returns 32 if mountpoint does not exist, map it to 1 to
+	# be compatible with findmnt(8)
+	if [ "$x" = "32" ]; then
+		x=1
+	fi
+	yo="$($TS_CMD_FINDMNT --kernel --mountpoint "$f" 2>&1)"
+	y=$?
+
+	[ "$x" = "$y" ] || ts_log "error: findmount vs. mountpoint: $x, $y, $f"
+	[ -z "$xo" ] || ts_log "error: mountpoint is not quiet: $x, $y, $f"
+	if [ "$y" = "0" -a "$yo" = "" ] || [ "$y" = "1" -a "$yo" != "" ]; then
+		ts_log "error, findmount return value vs. output: $x, $y, $f"
+	fi
+done
 
 # clean up
-$TS_CMD_UMOUNT $DIR_B
-rmdir $DIR_SRC $DIR_A $DIR_B
-
-$TS_CMD_UMOUNT $DIR_PRIVATE
-rmdir $DIR_PRIVATE $DIR_PRIVATE2
+$TS_CMD_UMOUNT $DIR_B || ts_log "error: umount DIR_B"
+rmdir $DIR_SRC $DIR_A $DIR_B || ts_log "error: rmdir DIR_B"
+$TS_CMD_UMOUNT $DIR_PRIVATE || ts_log "error: umount DIR_PRIVATE"
+rmdir $DIR_PRIVATE || ts_log "error: rmdir DIR_PRIVATE"
 
 ts_log "Success"
 ts_finalize
