revert, too many porting troubles right now. new irrelevant dependencies etc: add new files
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@51646 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/openvpn/tests/t_client.sh.in b/src/router/openvpn/tests/t_client.sh.in
--- a/src/router/openvpn/tests/t_client.sh.in
+++ b/src/router/openvpn/tests/t_client.sh.in
@@ -9,12 +9,8 @@
 # - writable current directory to create subdir for logs
 # - t_client.rc in current directory OR source dir that specifies tests
 # - for "ping4" checks: fping binary in $PATH
-# - for "ping6" checks: fping (4.0+) or fping6 binary in $PATH
+# - for "ping6" checks: fping6 binary in $PATH
 #
-
-# by changing this to 1 we can force automated builds to fail
-# that are expected to have all the prerequisites
-TCLIENT_SKIP_RC="${TCLIENT_SKIP_RC:-77}"
 
 srcdir="${srcdir:-.}"
 top_builddir="${top_builddir:-..}"
@@ -25,28 +21,25 @@ elif [ -r "${srcdir}"/t_client.rc ] ; then
 else
     echo "$0: cannot find 't_client.rc' in build dir ('${top_builddir}')" >&2
     echo "$0: or source directory ('${srcdir}'). SKIPPING TEST." >&2
-    exit "${TCLIENT_SKIP_RC}"
+    exit 77
 fi
 
 # Check for external dependencies
-FPING="fping"
-FPING6="fping6"
 which fping > /dev/null
 if [ $? -ne 0 ]; then
     echo "$0: fping is not available in \$PATH" >&2
-    exit "${TCLIENT_SKIP_RC}"
+    exit 77
 fi
 which fping6 > /dev/null
 if [ $? -ne 0 ]; then
-    echo "$0: fping6 is not available in \$PATH, assuming fping 4.0 or later" >&2
-    FPING="fping -4"
-    FPING6="fping -6"
+    echo "$0: fping6 is not available in \$PATH" >&2
+    exit 77
 fi
 
 KILL_EXEC=`which kill`
 if [ $? -ne 0 ]; then
     echo "$0: kill not found in \$PATH" >&2
-    exit "${TCLIENT_SKIP_RC}"
+    exit 77
 fi
 
 if [ ! -x "${top_builddir}/src/openvpn/openvpn" ]
@@ -63,12 +56,12 @@ fi
 
 if [ -z "$CA_CERT" ] ; then
     echo "CA_CERT not defined in 't_client.rc'. SKIP test." >&2
-    exit "${TCLIENT_SKIP_RC}"
+    exit 77
 fi
 
 if [ -z "$TEST_RUN_LIST" ] ; then
     echo "TEST_RUN_LIST empty, no tests defined.  SKIP test." >&2
-    exit "${TCLIENT_SKIP_RC}"
+    exit 77
 fi
 
 # Ensure PREFER_KSU is in a known state
@@ -98,7 +91,7 @@ else
     then
         echo "$0: this test must run be as root, or RUN_SUDO=... " >&2
         echo "      must be set correctly in 't_client.rc'. SKIP." >&2
-        exit "${TCLIENT_SKIP_RC}"
+        exit 77
     else
         # We have to use sudo. Make sure that we (hopefully) do not have
         # to ask the users password during the test. This is done to
@@ -108,7 +101,7 @@ else
 	    echo "$0: $RUN_SUDO $KILL_EXEC -0 succeeded, good."
 	else
 	    echo "$0: $RUN_SUDO $KILL_EXEC -0 failed, cannot go on. SKIP." >&2
-	    exit "${TCLIENT_SKIP_RC}"
+	    exit 77
 	fi
     fi
 fi
@@ -121,43 +114,17 @@ else
     exit 1
 fi
 
-# verbosity, defaults to "1"
-V="${V:-1}"
-
 exit_code=0
 
 # ----------------------------------------------------------
 # helper functions
 # ----------------------------------------------------------
 
-# output progress information
-#  depending on verbosity level, collect & print only on failure
-output_start()
-{
-    case $V in
-	0) outbuf="" ;;			# no per-test output at all
-	1) echo -e "$@"			# compact, details only on failure
-           outbuf="\n" ;;
-	*) echo -e "\n$@\n" ;;		# print all, with a bit formatting
-    esac
-}
-
-output()
-{
-    NO_NL=''; if [ "X$1" = "X-n" ] ; then NO_NL=$1 ; shift ; fi
-    case $V in
-	0) ;;				# no per-test output at all
-	1) outbuf="$outbuf$@" 		# print details only on failure
-	   test -z "$NO_NL" && outbuf="$outbuf\n"
-           ;;
-	*) echo -e $NO_NL "$@" ;;	# print everything
-    esac
-}
-
 # print failure message, increase FAIL counter
 fail()
 {
-    output "FAIL: $@\n"
+    echo ""
+    echo "FAIL: $@" >&2
     fail_count=$(( $fail_count + 1 ))
 }
 
@@ -249,8 +216,8 @@ run_ping_tests()
     if [ -z "$targetlist" ] ; then return ; fi
 
     case $proto in
-	4) cmd="$FPING" ;;
-	6) cmd="$FPING6" ;;
+	4) cmd=fping ;;
+	6) cmd=fping6 ;;
 	*) echo "internal error in run_ping_tests arg 1: '$proto'" >&2
 	   exit 1 ;;
     esac
@@ -262,10 +229,10 @@ run_ping_tests()
 
     for bytes in $sizes_list
     do
-	output "run IPv$proto ping tests ($want), $bytes byte packets..."
+	echo "run IPv$proto ping tests ($want), $bytes byte packets..."
 
-	echo "$cmd -b $bytes -C 20 -p 250 -q $fping_args $targetlist" >>$LOGDIR/$SUF:fping.out
-	$cmd -b $bytes -C 20 -p 250 -q $fping_args $targetlist >>$LOGDIR/$SUF:fping.out 2>&1
+	echo "$cmd -b $bytes -C 20 -p 250 -q $FPING_EXTRA_ARGS $targetlist" >>$LOGDIR/$SUF:fping.out
+	$cmd -b $bytes -C 20 -p 250 -q $FPING_EXTRA_ARGS $targetlist >>$LOGDIR/$SUF:fping.out 2>&1
 
 	# while OpenVPN is running, pings must succeed (want='want_ok')
 	# before OpenVPN is up, pings must NOT succeed (want='want_fail')
@@ -304,7 +271,6 @@ do
     eval expect_ifconfig6=\"\$EXPECT_IFCONFIG6_$SUF\"
     eval ping4_hosts=\"\$PING4_HOSTS_$SUF\"
     eval ping6_hosts=\"\$PING6_HOSTS_$SUF\"
-    eval fping_args=\"\$FPING_EXTRA_ARGS \$FPING_ARGS_$SUF\"
 
     # If EXCEPT_IFCONFIG* variables for this test are missing, run an --up
     # script to generate them dynamically.
@@ -314,32 +280,32 @@ do
         up=""
     fi
 
-    output_start "### test run $SUF: '$test_run_title' ###"
+    echo -e "\n### test run $SUF: '$test_run_title' ###\n"
     fail_count=0
 
     if [ -n "$test_prep" ]; then
-        output "running preparation: '$test_prep'"
+        echo -e "running preparation: '$test_prep'"
         eval $test_prep
     fi
 
-    output "save pre-openvpn ifconfig + route"
+    echo "save pre-openvpn ifconfig + route"
     get_ifconfig_route >$LOGDIR/$SUF:ifconfig_route_pre.txt
 
-    output "\nrun pre-openvpn ping tests - targets must not be reachable..."
+    echo -e "\nrun pre-openvpn ping tests - targets must not be reachable..."
     run_ping_tests 4 want_fail "$ping4_hosts"
     run_ping_tests 6 want_fail "$ping6_hosts"
     if [ "$fail_count" = 0 ] ; then
-        output "OK.\n"
+        echo -e "OK.\n"
     else
-	fail "make sure that ping hosts are ONLY reachable via VPN, SKIP test $SUF."
+	echo -e "FAIL: make sure that ping hosts are ONLY reachable via VPN, SKIP test $SUF".
 	SUMMARY_FAIL="$SUMMARY_FAIL $SUF"
 	exit_code=31
-	echo -e "$outbuf" ; continue
+	continue
     fi
 
     pidfile="${top_builddir}/tests/$LOGDIR/openvpn-$SUF.pid"
     openvpn_conf="$openvpn_conf --writepid $pidfile $up"
-    output " run openvpn $openvpn_conf"
+    echo " run openvpn $openvpn_conf"
     echo "# src/openvpn/openvpn $openvpn_conf" >$LOGDIR/$SUF:openvpn.log
     umask 022
     $RUN_SUDO "${top_builddir}/src/openvpn/openvpn" $openvpn_conf >>$LOGDIR/$SUF:openvpn.log &
@@ -362,25 +328,25 @@ do
 
     opid=`cat $pidfile`
     if [ -n "$opid" ]; then
-        output "  OpenVPN running with PID $opid"
+        echo "  OpenVPN running with PID $opid"
     else
-        output "  Could not read OpenVPN PID file"
+        echo "  Could not read OpenVPN PID file" >&2
     fi
 
     # If OpenVPN did not start
     if [ $ovpn_init_success -ne 1 -o -z "$opid" ]; then
-        output "$0:  OpenVPN did not initialize in a reasonable time"
+        echo "$0:  OpenVPN did not initialize in a reasonable time" >&2
         if [ -n "$opid" ]; then
            $RUN_SUDO $KILL_EXEC $opid
         fi
         $RUN_SUDO $KILL_EXEC $sudopid
-	output "tail -5 $SUF:openvpn.log"
-	output "`tail -5 $LOGDIR/$SUF:openvpn.log`"
-	fail "skip rest of sub-tests for test run $SUF."
+	echo "tail -5 $SUF:openvpn.log" >&2
+	tail -5 $LOGDIR/$SUF:openvpn.log >&2
+	echo -e "\nFAIL. skip rest of sub-tests for test run $SUF.\n" >&2
 	trap - 0 1 2 3 15
 	SUMMARY_FAIL="$SUMMARY_FAIL $SUF"
 	exit_code=30
-	echo -e "$outbuf" ; continue
+	continue
     fi
 
     # make sure openvpn client is terminated in case shell exits
@@ -388,21 +354,21 @@ do
     trap "$RUN_SUDO $KILL_EXEC $opid ; trap - 0 ; exit 1" 1 2 3 15
 
     # compare whether anything changed in ifconfig/route setup?
-    output "save ifconfig+route"
+    echo "save ifconfig+route"
     get_ifconfig_route >$LOGDIR/$SUF:ifconfig_route.txt
 
-    output -n "compare pre-openvpn ifconfig+route with current values..."
+    echo -n "compare pre-openvpn ifconfig+route with current values..."
     if diff $LOGDIR/$SUF:ifconfig_route_pre.txt \
 	    $LOGDIR/$SUF:ifconfig_route.txt >/dev/null
     then
 	fail "no differences between ifconfig/route before OpenVPN start and now."
     else
-	output " OK!\n"
+	echo -e " OK!\n"
     fi
 
     # post init script needed?
     if [ -n "$test_postinit" ]; then
-        output "running post-init cmd: '$test_postinit'"
+        echo -e "running post-init cmd: '$test_postinit'"
         eval $test_postinit
     fi
 
@@ -412,9 +378,9 @@ do
 
     run_ping_tests 4 want_ok "$ping4_hosts"
     run_ping_tests 6 want_ok "$ping6_hosts"
-    output "ping tests done.\n"
+    echo -e "ping tests done.\n"
 
-    output "stopping OpenVPN"
+    echo "stopping OpenVPN"
     $RUN_SUDO $KILL_EXEC $opid
     wait $!
     rc=$?
@@ -422,26 +388,23 @@ do
 	fail "OpenVPN return code $rc, expect 0"
     fi
 
-    output "\nsave post-openvpn ifconfig + route..."
+    echo -e "\nsave post-openvpn ifconfig + route..."
     get_ifconfig_route >$LOGDIR/$SUF:ifconfig_route_post.txt
 
-    output -n "compare pre- and post-openvpn ifconfig + route..."
+    echo -n "compare pre- and post-openvpn ifconfig + route..."
     if diff $LOGDIR/$SUF:ifconfig_route_pre.txt \
 	    $LOGDIR/$SUF:ifconfig_route_post.txt >$LOGDIR/$SUF:ifconfig_route_diff.txt
     then
-	output " OK.\n"
+	echo -e " OK.\n"
     else
-	output "\n\n" "`cat $LOGDIR/$SUF:ifconfig_route_diff.txt`" "\n"
-	fail "differences between pre- and post-ifconfig/route."
+	cat $LOGDIR/$SUF:ifconfig_route_diff.txt >&2
+	fail "differences between pre- and post-ifconfig/route"
     fi
     if [ "$fail_count" = 0 ] ; then
-        output "test run $SUF: all tests OK.\n"
+        echo -e "test run $SUF: all tests OK.\n"
 	SUMMARY_OK="$SUMMARY_OK $SUF"
     else
-	if [ "$V" -gt 0 ] ; then
-	    echo -e -n "$outbuf"
-	    echo -e "test run $SUF: $fail_count test failures. FAIL.\n"
-        fi
+	echo -e "test run $SUF: $fail_count test failures. FAIL.\n";
 	SUMMARY_FAIL="$SUMMARY_FAIL $SUF"
 	exit_code=30
     fi
