update btrfsprogs: add new files
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@62902 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/btrfsprogs/tests/nullb b/src/router/btrfsprogs/tests/nullb
--- a/src/router/btrfsprogs/tests/nullb
+++ b/src/router/btrfsprogs/tests/nullb
@@ -34,12 +34,12 @@ SYSFS='/sys/kernel/config/nullb'
 # setup
 
 function _error() {
-	echo "ERROR: $@"
+	echo "ERROR: $@" 1>&2
 	exit 1
 }
 
 function _warn() {
-	echo "WARNING: $@"
+	echo "WARNING: $@" 1>&2
 }
 
 function _msg() {
@@ -146,6 +146,9 @@ fi
 if [ "$CMD" = 'create' ]; then
 	_check_setup
 	index=$(_find_free_index)
+	if [ -z "$index" ]; then
+		exit 1
+	fi
 	name="nullb$index"
 	# size in MB
 	size=$(_parse_device_size "$@")
