update e2fsprogs
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@33175 52c4871e-980c-0410-b1e0-e73912ce01f8

Former-commit-id: ccff1abef9e5a0234623d2b5f5f41b84b714d1d9

diff --git a/src/router/e2fsprogs/lib/ss/mk_cmds.sh.in b/src/router/e2fsprogs/lib/ss/mk_cmds.sh.in
--- a/src/router/e2fsprogs/lib/ss/mk_cmds.sh.in
+++ b/src/router/e2fsprogs/lib/ss/mk_cmds.sh.in
@@ -3,8 +3,7 @@
 #
 
 datarootdir=@datarootdir@
-DIR="${DIR-@datadir@/ss}"
-SS_DIR="@SS_DIR@"
+DIR=@datadir@/ss
 AWK=@AWK@
 SED=@SED@
 
@@ -30,12 +29,8 @@ if test -n "$_SS_DIR_OVERRIDE" ; then
 fi
 
 if test ! -f $DIR/ct_c.sed || test ! -f $DIR/ct_c.awk ; then
-    DIR="$SS_DIR"
-#    echo "Falling back to $DIR..."
-    if test ! -f "$DIR/ct_c.sed" || test ! -f "$DIR/ct_c.awk" ; then
-	echo "mk_cmds: Couldn't find mk_cmds's template files."
-	exit 1
-    fi
+    echo "mk_cmds: Couldn't find mk_cmds's template files."
+    exit 1
 fi
 
 FILE="$1"
