update proftpd
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@21160 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/proftpd/configure b/src/router/proftpd/configure
--- a/src/router/proftpd/configure
+++ b/src/router/proftpd/configure
@@ -27910,7 +27910,8 @@ done
 
 
 
-for ac_func in bcopy crypt fdatasync fgetgrent fgetpwent fgetspent flock fpathconf freeaddrinfo futimes getpgid getpgrp nl_langinfo
+
+for ac_func in bcopy crypt fdatasync fgetgrent fgetpwent fgetspent flock fpathconf freeaddrinfo futimes getpgid getpgrp mkdtemp nl_langinfo
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 { echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -32861,16 +32862,16 @@ if test x"$pr_use_mysql" = xyes; then
   saved_libs="$LIBS"
   saved_cppflags="$CPPFLAGS"
 
-  { echo "$as_me:$LINENO: checking for MySQL's make_scrambled_password_323" >&5
-echo $ECHO_N "checking for MySQL's make_scrambled_password_323... $ECHO_C" >&6; }
-
-  # fiddle with CPPFLAGS, LDFLAGS
+  # Fiddle with CPPFLAGS, LDFLAGS
   CPPFLAGS="$CPPFLAGS $ac_build_addl_includes"
-  LDFLAGS="$LDFLAGS -lm -lmysqlclient -lz"
+  LDFLAGS="$LDFLAGS $ac_build_addl_libdirs"
 
     LIBS=`echo "$LIBS" | sed -e 's/-lsupp//g'`;
-  LIBS="$LIBS $ac_build_addl_libdirs"
+  LIBS="$LIBS -lm -lmysqlclient -lz"
 
+  # For Bug#3669, we need to check for make_scrambled_password_323.
+  { echo "$as_me:$LINENO: checking for MySQL's make_scrambled_password_323" >&5
+echo $ECHO_N "checking for MySQL's make_scrambled_password_323... $ECHO_C" >&6; }
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -32890,9 +32891,9 @@ int
 main ()
 {
 
-      char input[32];
-      char *output = NULL;
-      (void) make_scrambled_password_323(input, output);
+      char output[32];
+      char *input = NULL;
+      (void) make_scrambled_password_323(output, input);
 
   ;
   return 0;
@@ -32922,6 +32923,79 @@ echo "${ECHO_T}yes" >&6; }
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_MYSQL_MAKE_SCRAMBLED_PASSWORD_323 1
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+      { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+  # For Bug#3669 in the RedHat case, we need to check for
+  # my_make_scrambled_password.
+  { echo "$as_me:$LINENO: checking for MySQL's my_make_scrambled_password" >&5
+echo $ECHO_N "checking for MySQL's my_make_scrambled_password... $ECHO_C" >&6; }
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+      #ifdef HAVE_STDLIB_H
+      # include <stdlib.h>
+      #endif
+      #ifdef HAVE_SYS_TYPES_H
+      # include <sys/types.h>
+      #endif
+      #include <mysql.h>
+
+int
+main ()
+{
+
+      char output[32];
+      char *input = NULL;
+      size_t inputlen = 0;
+      my_make_scrambled_password(output, input, inputlen);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+      { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MYSQL_MY_MAKE_SCRAMBLED_PASSWORD 1
 _ACEOF
 
 
@@ -33211,6 +33285,21 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+
+  if test x"$openssl_cmdline" != xno; then
+    if `$openssl_cmdline version 2>/dev/null 1>&2`; then
+      openssl_cflags=`$openssl_cmdline version -f 2>/dev/null`
+      if test ! -z "$openssl_cflags"; then
+        # Look for the -pthread flag, indicating that this OpenSSL was built
+        # with threads support (see Bug#3795)
+        for openssl_cflag in $openssl_cflags; do
+          if test x"$openssl_cflag" = x"-pthread"; then
+            LIBS="$LIBS -pthread"
+          fi
+        done
+      fi
+    fi
+  fi
 fi
 
 if test x"$pr_use_postgres" = xyes; then
@@ -33224,10 +33313,10 @@ echo $ECHO_N "checking for Postgres's PQescapeStringConn... $ECHO_C" >&6; }
 
   # fiddle with CPPFLAGS, LDFLAGS
   CPPFLAGS="$CPPFLAGS $ac_build_addl_includes"
-  LDFLAGS="$LDFLAGS -lm -lpq"
+  LDFLAGS="$LDFLAGS $ac_build_addl_libdirs"
 
     LIBS=`echo "$LIBS" | sed -e 's/-lsupp//g'`;
-  LIBS="$LIBS $ac_build_addl_libdirs"
+  LIBS="$LIBS -lm -lpq"
 
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -33303,21 +33392,6 @@ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
   CPPFLAGS="$saved_cppflags"
   LDFLAGS="$saved_ldflags"
   LIBS="$saved_libs"
-
-  if test x"$openssl_cmdline" != xno; then
-    if `$openssl_cmdline version 2>/dev/null 1>&2`; then
-      openssl_cflags=`$openssl_cmdline version -f 2>/dev/null`
-      if test ! -z "$openssl_cflags"; then
-        # Look for the -pthread flag, indicating that this OpenSSL was built
-        # with threads support (see Bug#3795)
-        for openssl_cflag in $openssl_cflags; do
-          if test x"$openssl_cflag" = x"-pthread"; then
-            LIBS="$LIBS -pthread"
-          fi
-        done
-      fi
-    fi
-  fi
 fi
 
 for module in $ac_shared_modules ; do
