upgrade busybox to 1.13.1
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@11061 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/busybox/scripts/trylink b/src/router/busybox/scripts/trylink
--- a/src/router/busybox/scripts/trylink
+++ b/src/router/busybox/scripts/trylink
@@ -41,9 +41,8 @@ try() {
     printf "%s\n" "$*" >>$EXE.out
     printf "%s\n" "==========" >>$EXE.out
     $debug && echo "Trying: $*"
-    "$@" >>$EXE.out 2>&1
-    exitcode=$?
-    return $exitcode
+    $@ >>$EXE.out 2>&1
+    return $?
 }
 
 check_cc() {
@@ -141,12 +140,12 @@ while test "$LDLIBS"; do
 		-Wl,--start-group $O_FILES $A_FILES -Wl,--end-group \
 		$l_list
 	if test $? = 0; then
-	    echo " Library $one is not needed"
+	    echo " Library $one is not needed, excluding it"
 	    LDLIBS="$without_one"
 	    all_needed=false
 	    last_needed=false
 	else
-	    echo " Library $one is needed"
+	    echo " Library $one is needed, can't exclude it (yet)"
 	    last_needed=true
 	fi
     done
