update
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@42733 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/asterisk/contrib/scripts/ast_coredumper b/src/router/asterisk/contrib/scripts/ast_coredumper
--- a/src/router/asterisk/contrib/scripts/ast_coredumper
+++ b/src/router/asterisk/contrib/scripts/ast_coredumper
@@ -15,8 +15,9 @@ SYNOPSIS
 	$prog [ --help ] [ --running | --RUNNING ] [ --latest ]
 		[ --tarball-coredumps ] [ --delete-coredumps-after ]
 		[ --tarball-results ] [ --delete-results-after ]
-		[ --tarball-uniqueid="<uniqueid>" ]
+		[ --tarball-config ] [ --tarball-uniqueid="<uniqueid>" ]
 		[ --no-default-search ] [ --append-coredumps ]
+		[ --asterisk-bin="path" ]
 		[ <coredump> | <pattern> ... ]
 
 DESCRIPTION
@@ -50,7 +51,8 @@ DESCRIPTION
 		Create a coredump from the running asterisk instance and
 		process it along with any other coredumps found (if any).
 		WARNING: This WILL interrupt call processing.  You will be
-		asked to confirm.
+		asked to confirm.  The coredump will be written to /tmp if
+		$OUTPUTDIR is not defined.
 
 	--RUNNING
 		Same as --running but without the confirmation prompt.
@@ -63,9 +65,16 @@ DESCRIPTION
 		from the existing coredumps.
 
 	--tarball-coredumps
-		Creates a gzipped tarball of all coredumps processed.
-		The tarball name will be:
-		/tmp/asterisk.<timestamp>.coredumps.tar.gz
+		Creates a gzipped tarball of coredumps processed, their
+		results txt files and copies of /etc/os-release,
+		/usr/sbin/asterisk, /usr/lib(64)/libasterisk* and
+		/usr/lib(64)/asterisk as those files are needed to properly
+		examine the coredump.  The file will be named
+		$OUTPUTDIR/asterisk.<timestamp>.coredumps.tar.gz or
+		$OUTPUTDIR/asterisk-<uniqueid>.coredumps.tar.gz if
+		--tarball-uniqueid was specified.
+		WARNING:  This file could 1gb in size!
+		Mutually exclusive with --tartball-results
 
 	--delete-coredumps-after
 		Deletes all processed coredumps regardless of whether
@@ -74,13 +83,18 @@ DESCRIPTION
 	--tarball-results
 		Creates a gzipped tarball of all result files produced.
 		The tarball name will be:
-		/tmp/asterisk.<timestamp>.results.tar.gz
+		$OUTPUTDIR/asterisk.<timestamp>.results.tar.gz
+		Mutually exclusive with --tartball-coredumps
 
 	--delete-results-after
 		Deletes all processed results regardless of whether
 		a tarball was created.  It probably doesn't make sense
 		to use this option unless you have also specified
 		--tarball-results.
+
+	--tarball-config
+		Adds the contents of /etc/asterisk to the tarball created
+		with --tarball-coredumps or --tarball-results.
 
 	--tarball-uniqueid="<uniqueid>"
 		Normally DATEFORMAT is used to make the tarballs unique
@@ -95,6 +109,10 @@ DESCRIPTION
 	--append-coredumps
 		Append any coredumps specified on the command line to the
 		config file specified ones instead of overriding them.
+
+	--asterisk-binary
+		Path to the asterisk binary. Default: look for asterisk
+		in the PATH.
 
 	<coredump> | <pattern>
 		A list of coredumps or coredump search patterns.  Unless
@@ -118,6 +136,10 @@ DESCRIPTION
 
 NOTES
 	You must be root to use $prog.
+
+	$OUTPUTDIR can be read from the current environment or from the
+	ast_debug_tools.conf file described below.  If not specified,
+	work products are placed in the same directory as the core file.
 
 	The script relies on not only bash, but also recent GNU date and
 	gdb with python support.  *BSD operating systems may require
@@ -155,6 +177,12 @@ FILES
 	# anyway.
 	COREDUMPS=(/tmp/core[-._]asterisk!(*.txt) /tmp/core[-._]\$(hostname)!(*.txt))
 
+	# The directory to contain output files and work directories.
+	# For output from existing core files, the default is the
+	# directory that the core file is found in.  For core files
+	# produced from a running process, the default is /tmp.
+	OUTPUTDIR=/some/directory
+
 	# Date command for the "running" coredump and tarballs.
 	# DATEFORMAT will be executed to get the timestamp.
 	# Don't put quotes around the format string or they'll be
@@ -188,6 +216,7 @@ running=false
 RUNNING=false
 latest=false
 tarball_coredumps=false
+tarball_config=false
 delete_coredumps_after=false
 tarball_results=false
 delete_results_after=false
@@ -196,10 +225,28 @@ append_coredumps=false
 declare -a COREDUMPS
 declare -a ARGS_COREDUMPS
 
-# Read config files from least important to most important
-[ -f /etc/asterisk/ast_debug_tools.conf ] && source /etc/asterisk/ast_debug_tools.conf
-[ -f ~/ast_debug_tools.conf ] && source ~/ast_debug_tools.conf
-[ -f ./ast_debug_tools.conf ] && source ./ast_debug_tools.conf
+# readconf reads a bash-sourceable file and sets variables
+# that havn't already been set.  This allows variables set
+# on the command line or that are already in the environment
+# to take precedence over those read from the file.
+#
+# Setting the values can't be done in a subshell so you can't
+# just pipe the output of sed into the while.
+
+readconf() {
+	while read line ; do
+		v=${line%%=*}
+		[ -z "${!v}" ] && eval $line || :
+	done <<EOF
+$( sed -r -e "/\s*#/d" -e "/^\s*$/d" $1 )
+EOF
+}
+
+# Read config files from most important to least important.
+# Variable set on the command line or environment always take precedence.
+[ -f ./ast_debug_tools.conf ] && readconf ./ast_debug_tools.conf
+[ -f ~/ast_debug_tools.conf ] && readconf ~/ast_debug_tools.conf
+[ -f /etc/asterisk/ast_debug_tools.conf ] && readconf /etc/asterisk/ast_debug_tools.conf
 
 # For *BSD, the preferred gdb may be in /usr/local/bin so we
 # need to search for one that supports python.
@@ -214,6 +261,13 @@ done
 if [ -z "$GDB" ] ; then
 	echo "No suitable gdb was found in $PATH"
 	exit 1
+fi
+
+if [ -n "$OUTPUTDIR" ] ; then
+	if [ ! -d "$OUTPUTDIR" ] ; then
+		echo "OUTPUTDIR $OUTPUTDIR doesn't exists or is not a directory"
+		exit 1
+	fi
 fi
 
 if [ ${#COREDUMPS[@]} -eq 0 ] ; then
@@ -246,6 +300,9 @@ for a in "$@" ; do
 	--tarball-coredumps)
 		tarball_coredumps=true
 		;;
+	--tarball-config)
+		tarball_config=true
+		;;
 	--delete-coredumps-after)
 		delete_coredumps_after=true
 		;;
@@ -260,6 +317,9 @@ for a in "$@" ; do
 		;;
 	--tarball-uniqueid=*)
 		tarball_uniqueid=${a#*=}
+		;;
+	--asterisk-bin=*)
+		asterisk_bin=${a#*=}
 		;;
 	--help|-*)
 		print_help
@@ -312,38 +372,97 @@ fi
 # Timestamp to use for output files
 df=${tarball_uniqueid:-$(${DATEFORMAT})}
 
+if [ x"$asterisk_bin" = x ]; then
+	asterisk_bin=$(which asterisk)
+fi
+
 if $running || $RUNNING ; then
 	# We need to go through some gyrations to find the pid of the running
 	# MAIN asterisk process and not someone or something running asterisk -r.
-	# The pid file may NOT be in /var/run/asterisk so we need to find any
-	# running asterisk process and see if -C was specified on the command
-	# line.  The chances of more than 1 asterisk instance running with
-	# different -C options is so unlikely that we're going to ignore it.
-	#
-	# 'ps axo command' should work on Linux (back to CentOS6) and FreeBSD.
-	# If asterisk was started with -C, get the asterisk.conf file.
-	# If it wasn't, assume /etc/asterisk/asterisk.conf
-	astetcconf=`ps axo command | sed -n -r -e "s/.*asterisk\s+.*-C\s+([^ ]+).*/\1/gp" | tail -1`
-	[ x$astetcconf = x ] && astetcconf=/etc/asterisk/asterisk.conf
-	# Now parse out astrundir and cat asterisk.pid
-	astrundir=$(sed -n -r -e "s/astrundir\s+[=>]+\s+(.*)/\1/gp" $astetcconf)
-	pid=$(cat $astrundir/asterisk.pid 2>/dev/null || : )
-	if [ x$pid = x ] ; then
-		echo "Asterisk is not running"
+
+	unset pid
+
+	# Simplest case first...
+	pids=$(pgrep -f "$asterisk_bin")
+	pidcount=$(echo $pids | wc -w)
+
+	if [ $pidcount -eq 0 ] ; then
+		>&2 echo "Asterisk is not running"
+		exit 1
+	fi
+
+	# Single process, great.
+	if [ $pidcount -eq 1 ] ; then
+		pid=$pids
+		echo "Found a single asterisk instance running as process $pid"
+	fi
+
+	# More than 1 asterisk process running
+	if [ x"$pid" = x ] ; then
+		# More than 1 process running, let's try asking asterisk for it's
+		# pidfile
+		pidfile=$("$asterisk_bin" -rx "core show settings" 2>/dev/null | sed -n -r -e "s/^\s*pid file:\s+(.*)/\1/gpi")
+		# We found it
+		if [ x"$pidfile" != x -a -f "$pidfile" ] ; then
+			pid=$(cat "$pidfile")
+			echo "Found pidfile $pidfile with process $pid"
+		fi
+	fi
+
+	# It's possible that asterisk was started with the -C option which means the
+	# control socket and pidfile might not be where we expect.  We're going to
+	# have to parse the process arguments to see if -C was specified.
+	# The first process that has a -C argument determines which config
+	# file to use to find the pidfile of the main process.
+	# NOTE: The ps command doesn't quote command line arguments that it
+	# displays so we need to look in /proc/<pid>/cmdline.
+
+	if [ x"$pid" = x ] ; then
+		# BSDs might not mount /proc by default :(
+		mounted_proc=0
+		if uname -o | grep -qi "bsd" ; then
+			if ! mount | grep -qi "/proc" ; then
+				echo "Temporarily mounting /proc"
+				mounted_proc=1
+				mount -t procfs proc /proc
+			fi
+		fi
+
+		for p in $pids ; do
+			# Fields in cmdline are delimited by NULLs
+			astetcconf=$(sed -n -r -e "s/.*\x00-C\x00([^\x00]+).*/\1/gp" /proc/$p/cmdline)
+			if [ x"$astetcconf" != x ] ; then
+				pidfile=$("$asterisk_bin" -C "$astetcconf" -rx "core show settings" 2>/dev/null | sed -n -r -e "s/^\s*pid file:\s+(.*)/\1/gpi")
+				if [ x"$pidfile" != x -a -f "$pidfile" ] ; then
+					pid=$(cat "$pidfile")
+					echo "Found pidfile $pidfile the hard way with process $pid"
+					break
+				fi
+			fi
+		done
+		if [ $mounted_proc -eq 1 ] ; then
+			echo "Unmounting /proc"
+			umount /proc
+		fi
+	fi
+
+	if [ x"$pid" = x ] ; then
+		>&2 echo "Can't determine pid of the running asterisk instance"
+		exit 1
+	fi
+
+	if $RUNNING ; then
+		answer=Y
 	else
-		if $RUNNING ; then
-			answer=Y
-		else
-			read -p "WARNING:  Taking a core dump of the running asterisk instance will suspend call processing while the dump is saved.  Do you wish to continue? (y/N) " answer
-		fi
-		if [[ "$answer" =~ ^[Yy] ]] ; then
-			cf="/tmp/core-asterisk-running-$df"
-			echo "Dumping running asterisk process to $cf"
-			${GDB} -p $pid -q --batch --ex "gcore $cf" >/dev/null 2>&1
-			COREDUMPS+=("$cf")
-		else
-			echo "Skipping dump of running process"
-		fi
+		read -p "WARNING:  Taking a core dump of the running asterisk instance will suspend call processing while the dump is saved.  Do you wish to continue? (y/N) " answer
+	fi
+	if [[ "$answer" =~ ^[Yy] ]] ; then
+		cf="${OUTPUTDIR:-/tmp}/core-asterisk-running-$df"
+		echo "Dumping running asterisk process to $cf"
+		${GDB} ${asterisk_bin} -p $pid -q --batch --ex "gcore $cf" >/dev/null 2>&1
+		COREDUMPS+=("$cf")
+	else
+		echo "Skipping dump of running process"
 	fi
 fi
 
@@ -355,18 +474,27 @@ fi
 # Extract the gdb scripts from the end of this script
 # and save them to /tmp/.gdbinit
 
+gdbinit=${OUTPUTDIR:-/tmp}/.ast_coredumper.gdbinit
+
+trap "rm $gdbinit" EXIT
+
 ss=`egrep -n "^#@@@SCRIPTSTART@@@" $0 |cut -f1 -d:`
-tail -n +${ss} $0 >/tmp/.ast_coredumper.gdbinit
+tail -n +${ss} $0 >$gdbinit
 
 # Now iterate over the coredumps and dump the debugging info
 for i in ${!COREDUMPS[@]} ; do
 	cf=${COREDUMPS[$i]}
 	echo "Processing $cf"
-	${GDB} -n --batch -q --ex "source /tmp/.ast_coredumper.gdbinit" $(which asterisk) "$cf" 2>/dev/null | (
+
+	cfdir=`dirname ${cf}`
+	cfname=`basename ${cf}`
+	outputdir=${OUTPUTDIR:-${cfdir}}
+
+	${GDB} -n --batch -q --ex "source $gdbinit" "$asterisk_bin" "$cf" 2>/dev/null | (
 		of=/dev/null
 		while IFS= read line ; do
 			if [[ "$line" =~ !@!@!@!\ ([^\ ]+)\ !@!@!@! ]] ; then
-				of=${cf}-${BASH_REMATCH[1]}
+				of=${outputdir}/${cfname}-${BASH_REMATCH[1]}
 				of=${of//:/-}
 				rm -f "$of"
 				echo "Creating $of"
@@ -374,37 +502,59 @@ for i in ${!COREDUMPS[@]} ; do
 			echo -e $"$line" >> "$of"
 		done
 	)
-done
 
-if $tarball_coredumps ; then
-	tf=/tmp/asterisk-$df.coredumps.tar
-	echo "Creating $tf.gz"
-	for i in ${!COREDUMPS[@]} ; do
-		tar -uvf $tf "${COREDUMPS[@]}" 2>/dev/null
-	done
-	gzip $tf
-fi
+	if $tarball_coredumps ; then
+		cfname=${cfname//:/-}
+		tf=${outputdir}/${cfname}.tar.gz
+		echo "Creating ${tf}"
+
+		dest=${outputdir}/${cfname}.output
+		rm -rf ${dest} 2>/dev/null || :
+
+		libdir=usr/lib
+		[ -d /usr/lib64 ] && libdir+=64
+		mkdir -p ${dest}/tmp ${dest}/${libdir}/asterisk ${dest}/etc ${dest}/usr/sbin
+
+		ln -s ${cf} ${dest}/tmp/${cfname}
+		cp ${outputdir}/${cfname}*.txt ${dest}/tmp/
+		[ -f /etc/os-release ] && cp /etc/os-release ${dest}/etc/
+		if $tarball_config ; then
+			cp -a /etc/asterisk ${dest}/etc/
+		fi
+		cp -a /${libdir}/libasterisk* ${dest}/${libdir}/
+		cp -a /${libdir}/asterisk/* ${dest}/${libdir}/asterisk/
+		cp -a /usr/sbin/asterisk ${dest}/usr/sbin
+		rm -rf ${tf}
+		tar -chzf ${tf} --transform="s/^[.]/${cfname}/" -C ${dest} .
+		sleep 3
+		rm -rf ${dest}
+		echo "Created $tf"
+	elif $tarball_results ; then
+		cfname=${cfname//:/-}
+		tf=${outputdir}/${cfname}.tar.gz
+		echo "Creating ${tf}"
+
+		dest=${outputdir}/${cfname}.output
+		rm -rf ${dest} 2>/dev/null || :
+		mkdir -p ${dest}
+		cp ${outputdir}/${cfname}*.txt ${dest}/
+		if $tarball_config ; then
+			mkdir -p ${dest}/etc
+			cp -a /etc/asterisk ${dest}/etc/
+		fi
+		tar -chzf ${tf} --transform="s/^[.]/${cfname}/" -C ${dest} .
+		rm -rf ${dest}
+		echo "Created $tf"
+	fi
 
 if $delete_coredumps_after ; then
-	for i in ${!COREDUMPS[@]} ; do
-		rm -rf "${COREDUMPS[$i]}"
-	done
-fi
+		rm -rf "${cf}"
+	fi
 
-if $tarball_results ; then
-	tf=/tmp/asterisk-$df-results.tar
-	echo "Creating $tf.gz"
-	for i in ${!COREDUMPS[@]} ; do
-		tar -uvf $tf "${COREDUMPS[$i]//:/-}"-{brief,full,thread1,locks}.txt 2>/dev/null
-	done
-	gzip $tf
-fi
-
-if $delete_results_after ; then
-	for i in ${!COREDUMPS[@]} ; do
-		rm -rf "${COREDUMPS[$i]//:/-}"-{brief,full,thread1,locks}.txt
-	done
-fi
+	if $delete_results_after ; then
+		rm -rf "${cf//:/-}"-{brief,full,thread1,locks}.txt
+	fi
+done
 
 exit
 
@@ -431,20 +581,40 @@ class DumpAsteriskCommand(gdb.Command):
             pass
         print("!@!@!@! thread1.txt !@!@!@!\n")
         try:
+            gdb.execute("p $_siginfo", from_tty)
+            gdb.execute("info signal $_siginfo.si_signo")
+        except:
+            pass
+        try:
             gdb.execute("thread apply 1 bt full", from_tty)
         except:
             pass
         print("!@!@!@! brief.txt !@!@!@!\n")
+        try:
+            gdb.execute("p $_siginfo", from_tty)
+            gdb.execute("info signal $_siginfo.si_signo")
+        except:
+            pass
         try:
             gdb.execute("thread apply all bt", from_tty)
         except:
             pass
         print("!@!@!@! full.txt !@!@!@!\n")
         try:
+            gdb.execute("p $_siginfo", from_tty)
+            gdb.execute("info signal $_siginfo.si_signo")
+        except:
+            pass
+        try:
             gdb.execute("thread apply all bt full", from_tty)
         except:
             pass
         print("!@!@!@! locks.txt !@!@!@!\n")
+        try:
+            gdb.execute("p $_siginfo", from_tty)
+            gdb.execute("info signal $_siginfo.si_signo")
+        except:
+            pass
         try:
             gdb.execute("show_locks", from_tty)
         except:
diff --git a/src/router/asterisk/contrib/scripts/install_prereq b/src/router/asterisk/contrib/scripts/install_prereq
--- a/src/router/asterisk/contrib/scripts/install_prereq
+++ b/src/router/asterisk/contrib/scripts/install_prereq
@@ -19,29 +19,150 @@ usage() {
 }
 
 # Basic build system:
-PACKAGES_DEBIAN="build-essential"
+PACKAGES_DEBIAN="build-essential pkg-config"
 # Asterisk: basic requirements:
-PACKAGES_DEBIAN="$PACKAGES_DEBIAN libncurses-dev libz-dev libssl-dev libxml2-dev libsqlite3-dev uuid-dev uuid"
+PACKAGES_DEBIAN="$PACKAGES_DEBIAN libedit-dev libjansson-dev libsqlite3-dev uuid-dev libxml2-dev"
 # Asterisk: for addons:
-PACKAGES_DEBIAN="$PACKAGES_DEBIAN libcurl-dev libspeex-dev libspeexdsp-dev libogg-dev libvorbis-dev libasound2-dev portaudio19-dev libcurl4-openssl-dev"
-PACKAGES_DEBIAN="$PACKAGES_DEBIAN libpq-dev unixodbc-dev libsqlite0-dev libmysqlclient15-dev libneon27-dev libgmime-dev libusb-dev liblua5.1-0-dev lua5.1"
-PACKAGES_DEBIAN="$PACKAGES_DEBIAN libopenh323-dev libvpb-dev libgtk2.0-dev libmysqlclient-dev libbluetooth-dev libradiusclient-ng-dev freetds-dev"
-PACKAGES_DEBIAN="$PACKAGES_DEBIAN libsnmp-dev libiksemel-dev libcorosync-dev libnewt-dev libpopt-dev libical-dev libspandsp-dev libjack-dev"
-PACKAGES_DEBIAN="$PACKAGES_DEBIAN libresample-dev libc-client-dev binutils-dev libsrtp-dev libgsm1-dev libedit-dev doxygen libjansson-dev libldap-dev"
-PACKAGES_DEBIAN="$PACKAGES_DEBIAN subversion git libxslt1-dev automake libsrtp-dev libncurses5-dev python-dev"
-PACKAGES_RH="automake bzip2 gcc gcc-c++ patch ncurses-devel openssl-devel libxml2-devel unixODBC-devel libcurl-devel libogg-devel libvorbis-devel speex-devel"
-PACKAGES_RH="$PACKAGES_RH spandsp-devel freetds-devel net-snmp-devel iksemel-devel corosynclib-devel newt-devel popt-devel libtool-ltdl-devel lua-devel"
-PACKAGES_RH="$PACKAGES_RH sqlite-devel libsqlite3x-devel radiusclient-ng-devel portaudio-devel postgresql-devel libresample-devel neon-devel libical-devel"
-PACKAGES_RH="$PACKAGES_RH openldap-devel gmime22-devel sqlite2-devel mysql-devel bluez-libs-devel jack-audio-connection-kit-devel gsm-devel libedit-devel libuuid-devel"
-PACKAGES_RH="$PACKAGES_RH jansson-devel libsrtp-devel pjproject-devel subversion git libxslt-devel python-devel"
+PACKAGES_DEBIAN="$PACKAGES_DEBIAN libspeex-dev libspeexdsp-dev libogg-dev libvorbis-dev libasound2-dev portaudio19-dev libcurl4-openssl-dev xmlstarlet bison flex"
+PACKAGES_DEBIAN="$PACKAGES_DEBIAN libpq-dev unixodbc-dev libneon27-dev libgmime-2.6-dev liblua5.2-dev liburiparser-dev libxslt1-dev libssl-dev"
+PACKAGES_DEBIAN="$PACKAGES_DEBIAN libvpb-dev libmysqlclient-dev libbluetooth-dev libradcli-dev freetds-dev libosptk-dev libjack-jackd2-dev bash"
+PACKAGES_DEBIAN="$PACKAGES_DEBIAN libsnmp-dev libiksemel-dev libcorosync-common-dev libcpg-dev libcfg-dev libnewt-dev libpopt-dev libical-dev libspandsp-dev"
+PACKAGES_DEBIAN="$PACKAGES_DEBIAN libresample1-dev libc-client2007e-dev binutils-dev libsrtp0-dev libsrtp2-dev libgsm1-dev doxygen graphviz zlib1g-dev libldap2-dev"
+PACKAGES_DEBIAN="$PACKAGES_DEBIAN libcodec2-dev libfftw3-dev libsndfile1-dev libunbound-dev"
+# Asterisk: for the unpackaged below:
+PACKAGES_DEBIAN="$PACKAGES_DEBIAN wget subversion"
+# Asterisk: for ./configure --with-pjproject-bundled:
+PACKAGES_DEBIAN="$PACKAGES_DEBIAN bzip2 patch python-dev"
 
-PACKAGES_OBSD="popt gmake wget libxml libogg libvorbis curl iksemel spandsp speex iodbc freetds-0.63p1-msdblib mysql-client gmime sqlite sqlite3 jack libxslt"
-PACKAGES_FBSD="autoconf gcc binutils popt gmake wget libxml2 libogg libvorbis curl iksemel spandsp speex unixODBC freetds-devel mysql55-client gmime2 sqlite"
-PACKAGES_FBSD="$PACKAGES_FBSD sqlite3 libxslt jansson e2fsprogs-libuuid gsm libsrtp libsamplerate"
+# Basic build system:
+PACKAGES_RH="make gcc gcc-c++ pkgconfig"
+# Asterisk: basic requirements:
+PACKAGES_RH="$PACKAGES_RH libedit-devel jansson-devel libuuid-devel sqlite-devel libxml2-devel"
+# Asterisk: for addons:
+PACKAGES_RH="$PACKAGES_RH speex-devel speexdsp-devel libogg-devel libvorbis-devel alsa-lib-devel portaudio-devel libcurl-devel xmlstarlet bison flex"
+PACKAGES_RH="$PACKAGES_RH postgresql-devel unixODBC-devel neon-devel gmime-devel lua-devel uriparser-devel libxslt-devel openssl-devel"
+PACKAGES_RH="$PACKAGES_RH mysql-devel bluez-libs-devel radcli-devel freetds-devel jack-audio-connection-kit-devel bash"
+PACKAGES_RH="$PACKAGES_RH net-snmp-devel iksemel-devel corosynclib-devel newt-devel popt-devel libical-devel spandsp-devel"
+PACKAGES_RH="$PACKAGES_RH libresample-devel uw-imap-devel binutils-devel libsrtp-devel gsm-devel doxygen graphviz zlib-devel openldap-devel hoard"
+PACKAGES_RH="$PACKAGES_RH codec2-devel fftw-devel libsndfile-devel unbound-devel"
+# Asterisk: for the unpackaged below:
+PACKAGES_RH="$PACKAGES_RH wget subversion"
+# Asterisk: for ./configure --with-pjproject-bundled:
+PACKAGES_RH="$PACKAGES_RH bzip2 patch python-devel"
+
+# Basic build system:
+PACKAGES_SUSE="make gcc gcc-c++ pkg-config"
+# Asterisk: basic requirements:
+PACKAGES_SUSE="$PACKAGES_SUSE libedit-devel libjansson-devel libuuid-devel sqlite3-devel libxml2-devel"
+# Asterisk: for addons:
+PACKAGES_SUSE="$PACKAGES_SUSE speex-devel speexdsp-devel libogg-devel libvorbis-devel alsa-devel portaudio-devel libcurl-devel xmlstarlet bison flex"
+PACKAGES_SUSE="$PACKAGES_SUSE postgresql-devel unixODBC-devel libneon-devel gmime-devel lua-devel liburiparser-devel libxslt-devel libopenssl-devel"
+PACKAGES_SUSE="$PACKAGES_SUSE libmysqlclient-devel bluez-devel freeradius-client-devel freetds-devel bash"
+PACKAGES_SUSE="$PACKAGES_SUSE net-snmp-devel iksemel-devel libcorosync-devel newt-devel popt-devel libical-devel spandsp-devel"
+PACKAGES_SUSE="$PACKAGES_SUSE imap-devel libsrtp2-devel libgsm-devel doxygen graphviz zlib-devel openldap2-devel"
+PACKAGES_SUSE="$PACKAGES_SUSE codec2-devel fftw3-devel libsndfile-devel unbound-devel"
+# Asterisk: for the unpackaged below:
+PACKAGES_SUSE="$PACKAGES_SUSE wget subversion"
+# Asterisk: for ./configure --with-pjproject-bundled:
+PACKAGES_SUSE="$PACKAGES_SUSE bzip2 patch python-devel"
+
+# Basic build system:
+PACKAGES_ARCH="make gcc pkg-config"
+# Asterisk: basic requirements:
+PACKAGES_ARCH="$PACKAGES_ARCH libedit jansson libutil-linux libxml2 sqlite"
+# Asterisk: for addons:
+PACKAGES_ARCH="$PACKAGES_ARCH speex speexdsp libogg libvorbis alsa-lib portaudio curl xmlstarlet bison flex"
+PACKAGES_ARCH="$PACKAGES_ARCH postgresql-libs unixodbc neon gmime lua uriparser libxslt openssl"
+PACKAGES_ARCH="$PACKAGES_ARCH libmariadbclient bluez-libs radcli freetds bash"
+PACKAGES_ARCH="$PACKAGES_ARCH net-snmp libnewt popt libical spandsp"
+PACKAGES_ARCH="$PACKAGES_ARCH c-client binutils libsrtp gsm doxygen graphviz zlib libldap"
+PACKAGES_ARCH="$PACKAGES_ARCH fftw libsndfile unbound"
+# Asterisk: for the unpackaged below:
+PACKAGES_ARCH="$PACKAGES_ARCH wget subversion"
+# Asterisk: for ./configure --with-pjproject-bundled:
+PACKAGES_ARCH="$PACKAGES_ARCH bzip2 patch python2"
+
+# Basic build system:
+PACKAGES_GENTOO="sys-devel/make sys-devel/gcc dev-util/pkgconfig"
+# Asterisk: basic requirements:
+PACKAGES_GENTOO="$PACKAGES_GENTOO dev-libs/libedit dev-libs/jansson sys-libs/e2fsprogs-libs dev-libs/libxml2 dev-db/sqlite"
+# Asterisk: for addons:
+PACKAGES_GENTOO="$PACKAGES_GENTOO media-libs/speex media-libs/speexdsp media-libs/libogg media-libs/libvorbis media-libs/alsa-lib media-libs/portaudio net-misc/curl app-text/xmlstarlet sys-devel/bison sys-devel/flex"
+PACKAGES_GENTOO="$PACKAGES_GENTOO dev-db/postgresql dev-db/unixODBC net-libs/neon dev-libs/gmime dev-lang/lua dev-libs/uriparser dev-libs/libxslt dev-libs/openssl"
+PACKAGES_GENTOO="$PACKAGES_GENTOO virtual/libmysqlclient net-wireless/bluez net-dialup/radiusclient-ng dev-db/freetds app-shells/bash"
+PACKAGES_GENTOO="$PACKAGES_GENTOO net-analyzer/net-snmp dev-libs/iksemel sys-cluster/corosync dev-libs/newt dev-libs/popt dev-libs/libical media-libs/spandsp"
+PACKAGES_GENTOO="$PACKAGES_GENTOO net-libs/c-client sys-devel/binutils net-libs/libsrtp media-sound/gsm media-libs/libilbc app-doc/doxygen sys-libs/zlib net-nds/openldap"
+PACKAGES_GENTOO="$PACKAGES_GENTOO sci-libs/fftw media-libs/libsndfile net-dns/unbound"
+# Asterisk: for the unpackaged below:
+PACKAGES_GENTOO="$PACKAGES_GENTOO net-misc/wget dev-vcs/subversion"
+# Asterisk: for ./configure --with-pjproject-bundled:
+PACKAGES_GENTOO="$PACKAGES_GENTOO app-arch/bzip2 sys-devel/patch dev-lang/python:2.7"
+
+# Basic build system:
+PACKAGES_NBSD="gmake pkg-config"
+# Asterisk: basic requirements:
+PACKAGES_NBSD="$PACKAGES_NBSD editline jansson sqlite3 libuuid libxml2"
+# Asterisk: for addons:
+PACKAGES_NBSD="$PACKAGES_NBSD speex speexdsp libogg libvorbis alsa-lib portaudio-devel curl bison flex"
+PACKAGES_NBSD="$PACKAGES_NBSD postgresql10-client unixodbc neon gmime lua52 uriparser libxslt openssl"
+PACKAGES_NBSD="$PACKAGES_NBSD mysql-client radiusclient-ng freetds bash"
+PACKAGES_NBSD="$PACKAGES_NBSD net-snmp iksemel popt libical spandsp"
+PACKAGES_NBSD="$PACKAGES_NBSD imap-uw srtp gsm doxygen graphviz libzip openldap-client"
+PACKAGES_NBSD="$PACKAGES_NBSD codec2 fftw libsndfile unbound"
+# Asterisk: for the unpackaged below:
+PACKAGES_NBSD="$PACKAGES_NBSD wget subversion-base"
+# Asterisk: for ./configure --with-pjproject-bundled:
+PACKAGES_NBSD="$PACKAGES_NBSD bzip2 patch python27"
+
+# Basic build system:
+PACKAGES_OBSD="gmake"
+# Asterisk: basic requirements:
+PACKAGES_OBSD="$PACKAGES_OBSD libxml sqlite3 e2fsprogs jansson"
+# Asterisk: for addons:
+PACKAGES_OBSD="$PACKAGES_OBSD speex speexdsp libogg libvorbis portaudio-svn curl xmlstarlet bison"
+PACKAGES_OBSD="$PACKAGES_OBSD postgresql-client iodbc neon gmime lua%5.2 uriparser libxslt"
+PACKAGES_OBSD="$PACKAGES_OBSD mariadb-client radcli freetds"
+PACKAGES_OBSD="$PACKAGES_OBSD net-snmp iksemel popt libical spandsp"
+PACKAGES_OBSD="$PACKAGES_OBSD c-client libsrtp gsm doxygen graphviz"
+PACKAGES_OBSD="$PACKAGES_OBSD fftw3 libsndfile"
+# Asterisk: for the unpackaged below:
+PACKAGES_OBSD="$PACKAGES_OBSD wget subversion"
+# Asterisk: for ./configure --with-pjproject-bundled:
+PACKAGES_OBSD="$PACKAGES_OBSD bzip2 python%2"
+
+# Basic build system:
+PACKAGES_FBSD="gmake pkgconf"
+# Asterisk: basic requirements:
+PACKAGES_FBSD="$PACKAGES_FBSD libedit jansson e2fsprogs-libuuid sqlite3 libxml2"
+# Asterisk: for addons:
+PACKAGES_FBSD="$PACKAGES_FBSD speex speexdsp libogg libvorbis alsa-lib portaudio curl xmlstarlet bison flex"
+PACKAGES_FBSD="$PACKAGES_FBSD postgresql10-client unixODBC neon gmime26 lua52 uriparser libxslt openssl"
+PACKAGES_FBSD="$PACKAGES_FBSD mysql57-client radcli freetds"
+PACKAGES_FBSD="$PACKAGES_FBSD net-snmp iksemel corosync newt popt libical spandsp"
+PACKAGES_FBSD="$PACKAGES_FBSD cclient libbfd libsrtp gsm libilbc doxygen graphviz libzip openldap-client libhoard"
+PACKAGES_FBSD="$PACKAGES_FBSD codec2 fftw3 libsndfile unbound"
+# Asterisk: for the unpackaged below:
+PACKAGES_FBSD="$PACKAGES_FBSD wget subversion"
+# Asterisk: for ./configure --with-pjproject-bundled:
+PACKAGES_FBSD="$PACKAGES_FBSD bzip2 patch python"
+
+# Basic build system:
+PACKAGES_DBSD="gmake pkgconf"
+# Asterisk: basic requirements:
+PACKAGES_DBSD="$PACKAGES_DBSD libedit jansson e2fsprogs-libuuid sqlite3 libxml2"
+# Asterisk: for addons:
+PACKAGES_DBSD="$PACKAGES_DBSD speex speexdsp libogg libvorbis alsa-lib portaudio curl xmlstarlet bison flex"
+PACKAGES_DBSD="$PACKAGES_DBSD postgresql10-client unixODBC neon gmime26 lua52 uriparser libxslt libressl"
+PACKAGES_DBSD="$PACKAGES_DBSD mariadb101-client radcli freetds"
+PACKAGES_DBSD="$PACKAGES_DBSD net-snmp iksemel corosync newt popt libical spandsp"
+PACKAGES_DBSD="$PACKAGES_DBSD cclient binutils libsrtp gsm libilbc doxygen graphviz libzip openldap-client libhoard"
+PACKAGES_DBSD="$PACKAGES_DBSD codec2 fftw3 libsndfile unbound"
+# Asterisk: for the unpackaged below:
+PACKAGES_DBSD="$PACKAGES_DBSD wget subversion"
+# Asterisk: for ./configure --with-pjproject-bundled:
+PACKAGES_DBSD="$PACKAGES_DBSD bzip2 patch python"
 
 KVERS=`uname -r`
-
-JANSSON_VER=2.4
 
 case "$1" in
 test)
@@ -88,6 +209,29 @@ check_installed_rpms() {
 	done
 }
 
+check_installed_equery() {
+	for pack in "$@"
+	do
+		# equery --quiet list $pack
+		# is slower and
+		# would require the optional app-portage/gentoolkit
+		# /var/lib/portage/world would be the non-dep list
+		pack_with_version=${pack/:/-} # replace a possible version with '-'
+		if ! ls -d /var/db/pkg/${pack_with_version}* >/dev/null 2>/dev/null
+		then echo $pack
+		fi
+	done
+}
+
+check_installed_pacman() {
+	for pack in "$@"
+	do
+		if ! pacman -Q --explicit $pack >/dev/null 2>/dev/null
+		then echo $pack
+		fi
+	done
+}
+
 check_installed_pkgs() {
 	for pack in "$@"
 	do
@@ -106,9 +250,18 @@ check_installed_fpkgs() {
 	done
 }
 
+check_installed_zypper() {
+	for pack in "$@"
+	do
+		if ! zypper se -ixnC $pack >/dev/null 2>/dev/null
+		then echo $pack
+		fi
+	done
+}
+
 handle_debian() {
 	if ! [ -x "$(command -v aptitude)" ]; then
-		apt-get install aptitude
+		apt-get install -y aptitude
 	fi
 	extra_packs=`check_installed_debs $PACKAGES_DEBIAN`
 	$testcmd aptitude update
@@ -120,7 +273,32 @@ handle_debian() {
 handle_rh() {
 	extra_packs=`check_installed_rpms $PACKAGES_RH`
 	if [ x"$extra_packs" != "x" ] ; then
-		$testcmd yum install -y $extra_packs
+		$testcmd yum install --skip-broken --assumeyes $extra_packs
+	fi
+}
+
+handle_gentoo() {
+	extra_packs=`check_installed_equery $PACKAGES_GENTOO`
+	if [ x"$extra_packs" != "x" ] ; then
+		$testcmd emerge $extra_packs
+	fi
+}
+
+handle_arch() {
+	extra_packs=`check_installed_pacman $PACKAGES_ARCH`
+	if [ x"$extra_packs" != "x" ] ; then
+		$testcmd pacman -S --asexplicit --noconfirm $extra_packs
+	fi
+}
+
+handle_nbsd() {
+	extra_packs=`check_installed_pkgs $PACKAGES_NBSD`
+	if [ x"$extra_packs" != "x" ] ; then
+		if [ -z "$PKG_PATH" ] ; then
+			# see NetBSD Problem Report #48177
+			export PKG_PATH="http://cdn.NetBSD.org/pub/pkgsrc/packages/$(uname -s)/$(uname -p)/$(uname -r)/All"
+		fi
+		$testcmd pkg_add $extra_packs
 	fi
 }
 
@@ -138,11 +316,25 @@ handle_fbsd() {
 	fi
 }
 
+handle_dbsd() {
+	extra_packs=`check_installed_fpkgs $PACKAGES_DBSD`
+	if [ x"$extra_packs" != "x" ] ; then
+		$testcmd pkg install -y $extra_packs
+	fi
+}
+
+handle_SUSE() {
+	extra_packs=`check_installed_zypper $PACKAGES_SUSE`
+	if [ x"$extra_packs" != "x" ] ; then
+		$testcmd zypper install --no-confirm $extra_packs
+	fi
+}
+
 install_unpackaged() {
 	echo "*** Installing NBS (Network Broadcast Sound) ***"
 	svn co http://svn.digium.com/svn/nbs/trunk nbs-trunk
 	cd nbs-trunk
-	make && make install
+	make all install
 	cd ..
 
 	# Only install libresample if it wasn't installed via package
@@ -150,53 +342,32 @@ install_unpackaged() {
 		echo "*** Installing libresample ***"
 		svn co http://svn.digium.com/svn/thirdparty/libresample/trunk libresample-trunk
 		cd libresample-trunk
-		./configure && make && make install
+		./configure
+		make all install
 		cd ..
 	fi
 
-	# Only install Jansson if it wasn't installed via package
-	if ! test -f /usr/include/jansson.h; then
-		echo "*** Installing jansson ***"
-		wget -O - http://www.digip.org/jansson/releases/jansson-${JANSSON_VER}.tar.gz | zcat | tar -xf -
-		cd jansson-${JANSSON_VER}
-		./configure && make all && make install
-		cd ..
-		echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local.conf
-		/sbin/ldconfig
-	fi
-
-	# Only install libsrtp if it wasn't installed via package
+	# Only install libsrtp2 if it wasn't installed via package
 	if ! test -f /usr/include/srtp/srtp.h; then
-		echo "*** Installing libsrtp ***"
-		if [ ! -d libsrtp ]; then
-			git clone https://github.com/cisco/libsrtp.git
-			cd libsrtp
-		else
-			cd libsrtp
-			git pull
+		if ! test -f /usr/include/srtp2/srtp.h; then
+			echo "*** Installing libsrtp2 ***"
+			wget -O - http://github.com/cisco/libsrtp/archive/v2.tar.gz | zcat | tar -xf -
+			cd libsrtp-2
+			./configure --enable-openssl
+			make shared_library install
+			cd ..
+			if test -d /etc/ld.so.conf.d; then
+				echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local.conf
+			else # for example: Slackware 14.2
+				echo "/usr/local/lib" > /etc/ld.so.conf
+			fi
+			/sbin/ldconfig
 		fi
-		git checkout "1_5_x_throttle"
-		./configure --disable-debug --disable-stdout --enable-openssl
-		make shared_library uninstall install
-		cd ..
-		echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local.conf
-		/sbin/ldconfig
 	fi
 
-	# Only install pjproject if it wasn't installed via package
 	if ! test -f /usr/include/pjlib.h; then
-		echo "*** Installing pjproject ***"
-		if [ ! -d pjproject ]; then
-			git clone https://github.com/asterisk/pjproject.git
-			cd pjproject
-		else
-			cd pjproject
-			git pull
-		fi
-		./configure CFLAGS="-DNDEBUG -DPJ_HAS_IPV6=1" --enable-shared --with-external-speex --with-external-gsm --with-external-srtp --disable-sound --disable-resample && make && make install
-		cd ..
-		echo "/usr/local/lib" > /etc/ld.so.conf.d/usr_local.conf
-		/sbin/ldconfig
+		echo "PJProject not installed, yet. Therefore, please, run"
+		echo "./configure --with-pjproject-bundled"
 	fi
 }
 
@@ -214,25 +385,23 @@ OS=`uname -s`
 unsupported_distro=''
 
 # A number of distributions we don't (yet?) support.
-if [ "$OS" != 'Linux' -a "$OS" != 'OpenBSD' -a "$OS" != 'FreeBSD' ]; then
+if [ "$OS" != 'Linux' -a "$OS" != 'NetBSD' -a "$OS" != 'OpenBSD' -a "$OS" != 'FreeBSD' -a "$OS" != 'DragonFly' ]; then
 	echo >&2 "$0: Your OS ($OS) is currently not supported. Aborting."
 	exit 1
-fi
-
-if [ -f /etc/gentoo-release ]; then
-	unsupported_distro='Gentoo'
 fi
 
 if [ -f /etc/mandrake-release ]; then
 	unsupported_distro='Mandriva'
 fi
 
-if [ -f /etc/SuSE-release ]; then
-	unsupported_distro='SUSE'
-fi
-
-if [ -f /etc/slackware-version ]; then
-	unsupported_distro='Slackware'
+if [ -f /etc/slackware-version ] || ([ -f /etc/os-release ] && . /etc/os-release && [ "$ID" = "slackware" ]); then
+	echo >&2 "$0: Your distribution (Slackware) is currently not supported. Aborting. Try manually:"
+	# libedit requires a newer version than Slackware 14.2, for example Slackware-current
+	# or you build it manually: <http://thrysoee.dk/editline/>
+	echo >&2 "$0: # slackpkg install make gcc pkg-config libedit util-linux sqlite libxml2 patch wget"
+	# required for libjansson
+	echo >&2 "$0: # ./contrib/scripts/install_prereq install-unpackaged"
+	exit 1
 fi
 
 if [ "$unsupported_distro" != '' ]; then
@@ -245,10 +414,26 @@ if [ -r /etc/debian_version ]; then
 	handle_debian
 elif [ -r /etc/redhat-release ]; then
 	handle_rh
+elif [ -f /etc/SuSE-release -o -f /etc/novell-release ]; then
+	handle_SUSE
+elif [ -f /etc/os-release ] && . /etc/os-release && [ "$ID" = "opensuse" ]; then
+	handle_SUSE
+elif [ -r /etc/arch-release ]; then
+	handle_arch
+elif [ -f /etc/os-release ] && . /etc/os-release && [ "$ID_LIKE" = "archlinux" ]; then
+	handle_arch # $ID=arch
+elif [ -f /etc/gentoo-release ]; then
+	handle_gentoo
+elif [ -f /etc/os-release ] && . /etc/os-release && [ "$ID" = "gentoo" ]; then
+	handle_gentoo
+elif [ "$OS" = 'NetBSD' ]; then
+	handle_nbsd
 elif [ "$OS" = 'OpenBSD' ]; then
 	handle_obsd
 elif [ "$OS" = 'FreeBSD' ]; then
 	handle_fbsd
+elif [ "$OS" = 'DragonFly' ]; then
+	handle_dbsd
 fi
 
 if ! in_test_mode; then
