ignore this
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@55897 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/madwifi.dev/madwifi.dev/Makefile b/src/router/madwifi.dev/madwifi.dev/Makefile
--- a/src/router/madwifi.dev/madwifi.dev/Makefile
+++ b/src/router/madwifi.dev/madwifi.dev/Makefile
@@ -195,11 +195,11 @@ ifeq ($(strip $(BUS)),PCI)
 	fi
 endif
 	
-	@# check wireless extensions support is enabled
-	@if [ -z "$(CONFIG_NET_RADIO)$(CONFIG_WIRELESS_EXT)" ]; then \
-	    echo "FAILED"; \
-	    echo "Please enable wireless extensions."; \
-	    exit 1; \
-	fi
+#	@# check wireless extensions support is enabled
+#	@if [ -z "$(CONFIG_NET_RADIO)$(CONFIG_WIRELESS_EXT)" ]; then \
+#	    echo "FAILED"; \
+#	    echo "Please enable wireless extensions."; \
+#	    exit 1; \
+#	fi
 	
 	@echo "ok."
