fixed shell sip messaging
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@8736 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/milkfish/usr/sbin/milkfish_services b/src/router/milkfish/usr/sbin/milkfish_services
--- a/src/router/milkfish/usr/sbin/milkfish_services
+++ b/src/router/milkfish/usr/sbin/milkfish_services
@@ -183,6 +183,17 @@ case $1 in
 	mf_simple $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14 $15 $16 $17 $18 $19 $20 $21 $22 $23
 	exit 0
       ;;
+    simpledd)
+	CHECK2=${2:-NULL}
+	if [ $CHECK2 = "NULL" ] ; then
+	    mf_printhelp
+	    echo "ERROR: $CHECK2 is not a valid destination for service $1 - aborting"
+	    exit 1
+	fi
+	mf_feedback "Sending SIMPLE message to $2 ..."
+	mf_simpledd $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14 $15 $16 $17 $18 $19 $20 $21 $22 $23
+	exit 0
+      ;;
     phonebook)
 	mf_phonebook
 	exit 0
