revert broken busybox
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@30039 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/busybox/shell/ash_test/run-all b/src/router/busybox/shell/ash_test/run-all
--- a/src/router/busybox/shell/ash_test/run-all
+++ b/src/router/busybox/shell/ash_test/run-all
@@ -31,9 +31,8 @@ do_test()
 	    *.orig|*~) ;;
 	    #*) echo $x ; sh $x ;;
 	    *)
-	    echo -n "$1/$x: "
 	    sh "$x" >"$TOPDIR/$noslash-$x.fail" 2>&1 && \
-	    { echo "ok"; rm "$TOPDIR/$noslash-$x.fail"; } || echo "fail";
+	    { echo "$1/$x: ok"; rm "$TOPDIR/$noslash-$x.fail"; } || echo "$1/$x: fail";
 	    ;;
 	esac
     done
@@ -43,12 +42,11 @@ do_test()
 	test -x "$x" || continue
 	name="${x%%.tests}"
 	test -f "$name.right" || continue
-	echo -n "$1/$x: "
 	{
 	    "$THIS_SH" "./$x" >"$name.xx" 2>&1
 	    diff -u "$name.xx" "$name.right" >"$TOPDIR/$noslash-$x.fail" \
 	    && rm -f "$name.xx" "$TOPDIR/$noslash-$x.fail"
-	} && echo "ok" || echo "fail"
+	} && echo "$1/$x: ok" || echo "$1/$x: fail"
     done
     )
 }
