update softether: add new files
git-svn-id: svn://svn.dd-wrt.com/DD-WRT@39544 52c4871e-980c-0410-b1e0-e73912ce01f8

diff --git a/src/router/softether/configure b/src/router/softether/configure
--- a/src/router/softether/configure
+++ b/src/router/softether/configure
@@ -1,83 +1,54 @@
 #!/bin/sh
 
+set -e
+
 echo '---------------------------------------------------------------------'
 echo 'SoftEther VPN for Unix'
 echo
-echo 'Copyright (c) SoftEther VPN Project at University of Tsukuba, Japan.'
-echo 'Copyright (c) Daiyuu Nobori. All Rights Reserved.'
+echo 'Copyright (c) all contributors on SoftEther VPN project in GitHub.'
+echo 'Copyright (c) Daiyuu Nobori, SoftEther Project at University of Tsukuba, and SoftEther Corporation.'
 echo
-echo 'This program is free software; you can redistribute it and/or'
-echo 'modify it under the terms of the GNU General Public License'
-echo 'version 2 as published by the Free Software Foundation.'
+echo 'Licensed under the Apache License, Version 2.0 (the License).'
 echo
-echo 'Read and understand README.TXT, LICENSE.TXT and WARNING.TXT before use.'
+echo 'Read and understand README, LICENSE and WARNING before use.'
 echo '---------------------------------------------------------------------'
 echo
 
 echo 'Welcome to the corner-cutting configure script !'
 echo
-echo 'Select your operating system below:'
-echo ' 1: Linux'
-echo ' 2: FreeBSD'
-echo ' 3: Solaris'
-echo ' 4: Mac OS X'
-echo ' 5: OpenBSD'
-echo
-echo -n 'Which is your operating system (1 - 5) ? : '
-read TMP
-echo
-OS=""
-if test "$TMP" = "1"
-then
-	OS="linux"
-fi
-if test "$TMP" = "2"
-then
-	OS="freebsd"
-fi
-if test "$TMP" = "3"
-then
-	OS="solaris"
-fi
-if test "$TMP" = "4"
-then
-	OS="macos"
-fi
-if test "$TMP" = "5"
-then
-	OS="openbsd"
+
+if [ ! -d "tmp" ]; then
+  mkdir tmp
 fi
 
-if test "$OS" = ""
-then
-	echo "Wrong number."
-	exit 1
+if [ ! -z ${CMAKE_INSTALL_PREFIX+x} ]; then
+	CMAKE_FLAGS="-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
 fi
 
-echo 'Select your CPU bits below:'
-echo ' 1: 32-bit'
-echo ' 2: 64-bit'
-echo
-echo -n 'Which is the type of your CPU (1 - 2) ? : '
-read TMP
-echo
-CPU=""
-if test "$TMP" = "1"
-then
-	CPU="32bit"
-fi
-if test "$TMP" = "2"
-then
-	CPU="64bit"
+if [ -z ${OPENSSL_ROOT_DIR} ]; then
+	unameOut="$(uname -s)"
+	if [ "$unameOut" = "Darwin" ]; then
+		echo "Environment variable OPENSSL_ROOT_DIR not set, using default Homebrew path: /usr/local/opt/openssl/"
+		export OPENSSL_ROOT_DIR="/usr/local/opt/openssl/"
+	fi
 fi
 
-if test "$CPU" = ""
-then
-	echo "Wrong number."
-	exit 1
+if [ ! -z ${CPACK_GENERATOR+x} ]; then
+	echo "CPACK_GENERATOR is set, CPack will generate ${CPACK_GENERATOR} packages."
+	CMAKE_FLAGS="-DCPACK_GENERATOR=${CPACK_GENERATOR} ${CMAKE_FLAGS}"
+elif [ -x "$(command -v rpm)" ]; then
+	echo "'rpm' executable found, CPack will generate RPM packages."
+	CMAKE_FLAGS="-DCPACK_GENERATOR='RPM' ${CMAKE_FLAGS}"
+else
+	echo "'rpm' executable not found, CPack will generate DEB packages."
+	CMAKE_FLAGS="-DCPACK_GENERATOR='DEB' ${CMAKE_FLAGS}"
 fi
 
-cp src/makefiles/${OS}_${CPU}.mak Makefile
+echo ""
 
-echo "The Makefile is generated. Run 'make' to build SoftEther VPN."
+(cd tmp && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ${CMAKE_FLAGS} .. || exit 1)
 
+
+echo ""
+
+echo "The Makefile is generated. Run 'make -C tmp' to build SoftEther VPN."
